export const DE: Record<string, string> = {
  " — redémarrage requis": " — Neustart erforderlich",
  "(aucune sortie pour le moment)": "(noch keine Ausgabe)",
  "(indisponible)": "(nicht verfügbar)",
  "(vide)": "(leer)",
  "1 jour": "1 Tag",
  "1 semaine": "1 Woche",
  "30 derniers jours": "Letzte 30 Tage",
  "7 derniers jours": "Letzte 7 Tage",
  "90 derniers jours": "Letzte 90 Tage",
  "Accueil": "Startseite",
  "Action": "Aktion",
  "Activable dans les réglages UEFI/BIOS ; protège contre les rootkits de démarrage.": "Kann in den UEFI/BIOS-Einstellungen aktiviert werden; schützt vor Boot-Rootkits.",
  "Activer": "Aktivieren",
  "Activer l’assistant administrateur ?": "Administrator-Hilfsdienst aktivieren?",
  "Activité": "Aktivität",
  "Activé": "Aktiviert",
  "Actualiser": "Aktualisieren",
  "Afficher les mises à jour masquées dans Windows Update": "In Windows Update ausgeblendete Updates anzeigen",
  "Afficher quand même les versions en quarantaine": "Versionen in Quarantäne trotzdem anzeigen",
  "Afficher {n} de plus": "{n} weitere anzeigen",
  "Ajouter une règle": "Regel hinzufügen",
  "Analyse du {date}": "Analyse vom {date}",
  "Analyse en cours…": "Analyse läuft…",
  "Anciennes versions de pilotes": "Alte Treiberversionen",
  "Annuler": "Abbrechen",
  "Annuler le redémarrage": "Neustart abbrechen",
  "Annulé": "Abgebrochen",
  "Antivirus Microsoft Defender": "Microsoft Defender Antivirus",
  "Apparence": "Darstellung",
  "Application « {name} » fermée avant la mise à jour.": "Anwendung „{name}“ vor dem Update geschlossen.",
  "Application à fermer": "Zu schließende Anwendung",
  "Applications": "Anwendungen",
  "Applications Python isolées installées avec pipx": "Mit pipx installierte isolierte Python-Anwendungen",
  "Applications du Microsoft Store (via winget, source msstore)": "Microsoft Store-Apps (über winget, Quelle msstore)",
  "Applique ses réglages par-dessus les paramètres. Aussi accessible depuis la zone de notification.": "Wendet seine Überschreibungen auf die Einstellungen an. Auch über den Infobereich verfügbar.",
  "Architecture": "Architektur",
  "Arguments supplémentaires pour l’installeur": "Zusätzliche Installer-Argumente",
  "Assistant administrateur": "Administrator-Hilfsdienst",
  "Associer": "Verknüpfen",
  "Associer « {name} » à un paquet winget": "„{name}“ mit einem winget-Paket verknüpfen",
  "Au démarrage, une source vérifiée plus récemment que ce délai n’est pas réinterrogée.": "Beim Start werden Quellen, die vor kürzerer Zeit geprüft wurden, nicht erneut abgefragt.",
  "Aucun": "Keine",
  "Aucun outil connu": "Kein bekanntes Tool",
  "Aucun paquet trouvé.": "Kein Paket gefunden.",
  "Aucun pilote Studio publié pour ce GPU : UpKeep propose la branche Game Ready.": "Für diese GPU wird kein Studio-Treiber veröffentlicht: UpKeep bietet den Game-Ready-Zweig an.",
  "Aucun problème détecté.": "Keine Probleme erkannt.",
  "Aucun produit suivi détecté.": "Kein überwachtes Produkt erkannt.",
  "Aucun périphérique Logitech, Razer, SteelSeries ou Corsair connecté.": "Kein Logitech-, Razer-, SteelSeries- oder Corsair-Gerät angeschlossen.",
  "Aucun résultat.": "Keine Ergebnisse.",
  "Aucune activité.": "Keine Aktivität.",
  "Aucune mise à jour en attente.": "Keine ausstehenden Updates.",
  "Aucune règle.": "Keine Regeln.",
  "Aucune.": "Keine.",
  "UpKeep surveille les mises à jour de vos logiciels, de Windows, de vos pilotes et de votre BIOS, et les installe quand vous le décidez.": "UpKeep überwacht Updates für Ihre Software, Windows, Treiber und BIOS und installiert sie, wenn Sie es entscheiden.",
  "UpKeep tourne avec les droits administrateur.": "UpKeep läuft mit Administratorrechten.",
  "UpKeep — vérification en cours…": "UpKeep — Prüfung läuft…",
  "UpKeep — {n} mise(s) à jour disponible(s)": "UpKeep — {n} Update(s) verfügbar",
  "Automatiques en pause : {why}": "Automatische Updates pausiert: {why}",
  "Automatisation": "Automatisierung",
  "BIOS installé :": "Installiertes BIOS:",
  "BIOS publié sur le site de support ASUS pour votre modèle": "Auf der ASUS-Supportseite für Ihr Modell veröffentlichtes BIOS",
  "BIOS, firmware et pilotes Dell via dcu-cli": "Dell-BIOS, Firmware und Treiber über dcu-cli",
  "BIOS, firmware et pilotes HP analysés par HP Image Assistant": "HP-BIOS, Firmware und Treiber, analysiert von HP Image Assistant",
  "Batterie": "Akku",
  "Batterie : {n} %": "Akku: {n} %",
  "Batterie minimale pour un firmware/BIOS": "Mindestakkustand für Firmware/BIOS",
  "Batterie à {n} % : il faut au moins {min} % pour un firmware/BIOS.": "Akku bei {n} %: Für Firmware/BIOS sind mindestens {min} % erforderlich.",
  "Bienvenue dans UpKeep": "Willkommen bei UpKeep",
  "Binaires Rust installés avec « cargo install »": "Mit „cargo install“ installierte Rust-Programme",
  "BitLocker sera suspendu pour un redémarrage.": "BitLocker wird für einen Neustart angehalten.",
  "Bloquer en connexion limitée": "Bei getakteter Verbindung blockieren",
  "Branche des pilotes NVIDIA": "NVIDIA-Treiberzweig",
  "Branchez le chargeur secteur avant une mise à jour de firmware/BIOS.": "Schließen Sie vor einem Firmware/BIOS-Update das Netzteil an.",
  "CVE corrigées en attente": "Ausstehende CVE-Korrekturen",
  "Cache de Windows Update": "Windows Update-Cache",
  "Cache des résultats": "Ergebnis-Cache",
  "Cache npm": "npm-Cache",
  "Cache pip": "pip-Cache",
  "Calcul de l’espace récupérable…": "Freigebbarer Speicher wird berechnet…",
  "Carte mère": "Mainboard",
  "Cartes graphiques": "Grafikkarten",
  "Catalogue constructeur Lenovo via le module PowerShell LSUClient": "Lenovo-Katalog über das PowerShell-Modul LSUClient",
  "Ce GPU Intel n’utilise pas le pilote unifié Xe : vérification automatique indisponible.": "Diese Intel-GPU nutzt nicht den einheitlichen Xe-Treiber: automatische Prüfung nicht verfügbar.",
  "Ce PC est configuré pour un serveur WSUS ({srv}) ; UpKeep interroge tout de même Windows Update directement.": "Dieser PC ist für einen WSUS-Server ({srv}) konfiguriert; UpKeep fragt Windows Update dennoch direkt ab.",
  "Ce PC est géré par une organisation (Intune / MDM) : certaines mises à jour peuvent être bloquées par stratégie.": "Dieser PC wird von einer Organisation verwaltet (Intune / MDM): Einige Updates können durch Richtlinien blockiert sein.",
  "Ce pilote vise un périphérique déjà branché un jour mais absent aujourd’hui.": "Dieser Treiber betrifft ein Gerät, das einmal angeschlossen war, heute aber fehlt.",
  "Ces 7 derniers jours": "Letzte 7 Tage",
  "Ces applications seront fermées avant la mise à jour : {list}": "Diese Anwendungen werden vor dem Update geschlossen: {list}",
  "Ces programmes ne sont suivis par aucun gestionnaire. Associez-les à un paquet winget pour qu’UpKeep surveille leurs mises à jour.": "Diese Programme werden von keinem Paketmanager verfolgt. Verknüpfen Sie sie mit einem winget-Paket, damit UpKeep ihre Updates überwacht.",
  "Cette page a rencontré une erreur": "Auf dieser Seite ist ein Fehler aufgetreten",
  "L’interface a rencontré une erreur": "In der Oberfläche ist ein Fehler aufgetreten",
  "Champ": "Feld",
  "Charge": "Ladung",
  "Chargement des détails…": "Details werden geladen…",
  "Chargement…": "Wird geladen…",
  "Charger les versions": "Versionen laden",
  "Chiffrement BitLocker du disque système": "BitLocker-Verschlüsselung des Systemlaufwerks",
  "Choisir": "Auswählen",
  "Choisir…": "Auswählen…",
  "Chrome, Edge et Firefox comparés à la dernière version stable publiée": "Chrome, Edge und Firefox im Vergleich mit der neuesten stabilen Version",
  "Clair": "Hell",
  "Colonnes et affichage": "Spalten und Anzeige",
  "Comme les paramètres": "Wie in den Einstellungen",
  "Commencer": "Loslegen",
  "Composants, firmwares et outils constructeur.": "Komponenten, Firmware und Herstellertools.",
  "Confirmer": "Bestätigen",
  "Confirmer le téléchargement": "Download bestätigen",
  "Confirmer l’installation": "Installation bestätigen",
  "Connexion limitée": "Getaktete Verbindung",
  "Contrôle": "Kontrolle",
  "Contrôle de compte d’utilisateur (UAC)": "Benutzerkontensteuerung (UAC)",
  "Copier": "Kopieren",
  "Copier le journal": "Protokoll kopieren",
  "Copier l’identifiant": "ID kopieren",
  "Copié !": "Kopiert!",
  "Correct": "OK",
  "Crée une tâche planifiée Windows (sans droits administrateur) qui lance une vérification à la fréquence choisie.": "Erstellt eine Windows-Aufgabe (ohne Administratorrechte), die im gewählten Intervall eine Prüfung ausführt.",
  "Créer un rapport de diagnostic": "Diagnosebericht erstellen",
  "Créer…": "Erstellen…",
  "Date": "Datum",
  "Dernier pilote Game Ready ou Studio publié par NVIDIA pour votre carte graphique": "Neuester Game-Ready- oder Studio-Treiber von NVIDIA für Ihre Grafikkarte",
  "Dernière version du cycle": "Neueste Version des Zyklus",
  "Dernière vérification : {last} · prochaine {next}": "Letzte Prüfung: {last} · nächste {next}",
  "Des mises à jour attendent un redémarrage pour être finalisées.": "Einige Updates warten auf einen Neustart, um abgeschlossen zu werden.",
  "Des mises à jour sont disponibles": "Updates sind verfügbar",
  "Descendre": "Nach unten",
  "Description": "Beschreibung",
  "Diagnostic": "Diagnose",
  "Dim": "So",
  "Disponible": "Verfügbar",
  "Disques et firmware": "Laufwerke und Firmware",
  "Dissocier ({id})": "Verknüpfung aufheben ({id})",
  "Docker n’est pas démarré : les images ne peuvent pas être vérifiées.": "Docker läuft nicht: Images können nicht geprüft werden.",
  "Dossier des téléchargements": "Download-Ordner",
  "Dupliquer": "Duplizieren",
  "Durée": "Dauer",
  "Début": "Beginn",
  "Délai de {n} min dépassé": "Zeitüberschreitung nach {n} min",
  "Délai max (min)": "Zeitlimit (min)",
  "Démarrage sécurisé (Secure Boot)": "Secure Boot",
  "Démarre réduit dans la zone de notification (version installée uniquement).": "Startet minimiert im Infobereich (nur installierte Version).",
  "Démarrer masqué": "Versteckt starten",
  "Déroule tout le processus (file, élévation, journal) sans rien installer : idéal pour vérifier ce qui se passerait.": "Führt den gesamten Ablauf (Warteschlange, Erhöhung, Protokoll) aus, ohne etwas zu installieren: ideal, um zu sehen, was passieren würde.",
  "Désactiver": "Deaktivieren",
  "Désactivé": "Deaktiviert",
  "Désactivée": "Deaktiviert",
  "Désépingler": "Lösen",
  "Détail": "Detail",
  "Détails": "Details",
  "Développement": "Entwicklung",
  "Empreinte SHA-256 différente de celle publiée par ASUS.": "SHA-256-Prüfsumme weicht von der von ASUS veröffentlichten ab.",
  "En attente": "In Warteschlange",
  "En cours": "Läuft",
  "En cours…": "Läuft…",
  "En pause actuellement : {why}": "Derzeit pausiert: {why}",
  "En quarantaine": "In Quarantäne",
  "En quarantaine jusqu’au {date} (version récente).": "In Quarantäne bis {date} (neue Version).",
  "Enregistrez votre travail : Windows redémarre immédiatement.": "Speichern Sie Ihre Arbeit: Windows startet sofort neu.",
  "Entrée": "Eingabe",
  "Erreur": "Fehler",
  "Erreur réseau : nouvelle tentative dans 30 s.": "Netzwerkfehler: neuer Versuch in 30 s.",
  "Espace disque insuffisant : {free} Go libres, environ {need} Go nécessaires.": "Nicht genug Speicherplatz: {free} GB frei, etwa {need} GB benötigt.",
  "Espace récupérable : {size}": "Freigebbarer Speicher: {size}",
  "Exiger le secteur pour un firmware/BIOS": "Netzteil für Firmware/BIOS erforderlich",
  "Export / import": "Export / Import",
  "Export annulé.": "Export abgebrochen.",
  "Export lancé (voir Activité).": "Export gestartet (siehe Aktivität).",
  "Exporter": "Exportieren",
  "Exporter en CSV": "Als CSV exportieren",
  "Exporté vers {path}": "Exportiert nach {path}",
  "Extensions Visual Studio Code dont une version plus récente existe sur le Marketplace": "Visual Studio Code-Erweiterungen mit neuerer Version im Marketplace",
  "Faille activement exploitée : mise à jour urgente": "Aktiv ausgenutzte Sicherheitslücke: dringendes Update",
  "Failles activement exploitées": "Aktiv ausgenutzte Sicherheitslücken",
  "Fermer": "Schließen",
  "Fichier de paramètres UpKeep invalide.": "Ungültige UpKeep-Einstellungsdatei.",
  "Fichiers déjà installés conservés par Windows Update (retéléchargés si besoin).": "Von Windows Update aufbewahrte, bereits installierte Dateien (bei Bedarf erneut heruntergeladen).",
  "Fichiers texte mis à jour en continu (1 Mo maximum, 3 fichiers conservés).": "Fortlaufend aktualisierte Textdateien (max. 1 MB, 3 Dateien aufbewahrt).",
  "Filtres": "Filter",
  "Fin": "Ende",
  "Fin de support": "Supportende",
  "Fins de support": "Supportende",
  "Fins de support (endoflife.date), failles exploitées (CISA KEV), vulnérabilités des logiciels de bureau (NVD).": "Supportende (endoflife.date), ausgenutzte Sicherheitslücken (CISA KEV), Sicherheitslücken in Desktop-Software (NVD).",
  "Firmware": "Firmware",
  "Firmware & BIOS": "Firmware & BIOS",
  "Forfait mobile, partage de connexion…": "Mobile Daten, Tethering…",
  "Fréquence": "Häufigkeit",
  "Fréquence de vérification": "Prüfhäufigkeit",
  "Fréquence globale": "Globale Häufigkeit",
  "Gestionnaire de paquets Chocolatey (nécessite les droits administrateur)": "Paketmanager Chocolatey (erfordert Administratorrechte)",
  "Gestionnaire de paquets Windows (Microsoft)": "Windows-Paket-Manager (Microsoft)",
  "Gestionnaires de paquets, Windows Update, pilotes graphiques et outils constructeur.": "Paketmanager, Windows Update, Grafiktreiber und Herstellertools.",
  "Go": "GB",
  "Graphique": "Diagramm",
  "Graphique en barres empilées": "Gestapeltes Balkendiagramm",
  "Grouper": "Gruppieren",
  "Général": "Allgemein",
  "Gérer les sources": "Quellen verwalten",
  "Heure": "Uhrzeit",
  "Identifiant": "ID",
  "Identifiant matériel inconnu pour ce pilote.": "Unbekannte Hardware-ID für diesen Treiber.",
  "Ignorer": "Ignorieren",
  "Ignorer cette version": "Diese Version ignorieren",
  "Ignorées": "Ignoriert",
  "Ignorées & épinglées": "Ignoriert & fixiert",
  "Images locales dont une version plus récente est publiée sur Docker Hub": "Lokale Images mit neuerem Build auf Docker Hub",
  "Import lancé (voir Activité).": "Import gestartet (siehe Aktivität).",
  "Importer": "Importieren",
  "Inconnu": "Unbekannt",
  "Infos": "Info",
  "Installateur en ligne de commande pour Windows": "Kommandozeilen-Installer für Windows",
  "Installation": "Installation",
  "Installation depuis le site d’Intel (l’installeur Intel n’est pas silencieux).": "Von der Intel-Website installiert (der Intel-Installer ist nicht still).",
  "Installation du module LSUClient depuis PowerShell Gallery (portée utilisateur)…": "Installation des Moduls LSUClient aus der PowerShell Gallery (Benutzerbereich)…",
  "Installation impossible": "Installation nicht möglich",
  "Installation via l’assistant administrateur (sans fenêtre UAC).": "Über den Administrator-Hilfsdienst installiert (ohne UAC-Abfrage).",
  "Installations en cours, file d’attente et historique.": "Laufende Installationen, Warteschlange und Verlauf.",
  "Installations en parallèle": "Parallele Installationen",
  "Installe sans intervention les mises à jour des sources et paquets marqués « automatique » (Sources › Réglages, ou panneau de détail).": "Installiert Updates von Quellen und Paketen, die als „automatisch“ markiert sind, ohne Eingriff (Quellen › Einstellungen oder Detailbereich).",
  "Installer (une fenêtre UAC)": "Installieren (eine UAC-Abfrage)",
  "Installer Dell Command | Update (winget)": "Dell Command | Update installieren (winget)",
  "Installer HP Image Assistant (winget)": "HP Image Assistant installieren (winget)",
  "Installer Intel DSA (winget)": "Intel DSA installieren (winget)",
  "Installer LSUClient pour tous les utilisateurs": "LSUClient für alle Benutzer installieren",
  "Installer ces mises à jour ? (o/N) ": "Diese Updates installieren? (j/N)",
  "Installer cette version": "Diese Version installieren",
  "Installer le module LSUClient": "Modul LSUClient installieren",
  "Installer le module Microsoft.WinGet.Client": "Modul Microsoft.WinGet.Client installieren",
  "Installer sans fenêtre UAC": "Ohne UAC-Abfragen installieren",
  "Installer une version précise": "Bestimmte Version installieren",
  "Installer {n} élément(s)": "{n} Element(e) installieren",
  "Installeur déjà téléchargé : {path}": "Installer bereits heruntergeladen: {path}",
  "Installeurs temporaires de winget": "Temporäre winget-Installer",
  "Installeurs temporaires de winget supprimés.": "Temporäre winget-Installer gelöscht.",
  "Installeurs téléchargés par winget lors des mises à jour.": "Von winget bei Updates heruntergeladene Installer.",
  "Installé le": "Installiert am",
  "Installée": "Installiert",
  "Installées": "Installiert",
  "Intel DSA est installé : il gère aussi les pilotes Wi-Fi et Bluetooth Intel.": "Intel DSA ist installiert: Es verwaltet auch die Intel-WLAN- und Bluetooth-Treiber.",
  "Interrompre": "Unterbrechen",
  "Interrompu": "Unterbrochen",
  "Interruption demandée : le processus administrateur peut terminer l’étape en cours.": "Abbruch angefordert: Der Administratorprozess kann den aktuellen Schritt noch abschließen.",
  "Interruption demandée…": "Abbruch angefordert…",
  "Inventaire": "Inventar",
  "Jamais": "Nie",
  "Jamais automatique": "Nie automatisch",
  "Jamais automatiquement": "Nie automatisch",
  "Jamais bloquer": "Nie blockieren",
  "Java (OpenJDK)": "Java (OpenJDK)",
  "Jeu": "Do",
  "Jokers : * = n’importe quelle suite, ? = un caractère. Exemples : *.Preview, Microsoft.*, *chrome*.": "Platzhalter: * = beliebige Zeichenfolge, ? = ein Zeichen. Beispiele: *.Preview, Microsoft.*, *chrome*.",
  "Journal": "Protokoll",
  "Journal de diagnostic — {name}": "Diagnoseprotokoll — {name}",
  "Journal des modifications": "Änderungsprotokoll",
  "Journaux d’UpKeep": "UpKeep-Protokolle",
  "Jours": "Tage",
  "Ko": "KB",
  "Lancer avec Windows": "Mit Windows starten",
  "Lancer avec Windows (réduit dans la zone de notification)": "Mit Windows starten (minimiert im Infobereich)",
  "Langue": "Sprache",
  "Langue de Windows": "Windows-Sprache",
  "Le firmware de ces périphériques se met à jour depuis le logiciel du fabricant.": "Die Firmware dieser Geräte wird über die Software des Herstellers aktualisiert.",
  "Le pilote installé pour « {name} » sera retiré du magasin de pilotes ; Windows reviendra à la version précédente. Un redémarrage peut être nécessaire.": "Der für „{name}“ installierte Treiber wird aus dem Treiberspeicher entfernt; Windows kehrt zur vorherigen Version zurück. Ein Neustart kann erforderlich sein.",
  "Lecture de Secure Boot, TPM et BitLocker…": "Secure Boot, TPM und BitLocker werden gelesen…",
  "Lecture de l’état de sécurité…": "Sicherheitsstatus wird gelesen…",
  "Lecture des programmes installés…": "Installierte Programme werden gelesen…",
  "Lecture du matériel…": "Hardware wird gelesen…",
  "Les firmwares/BIOS ne sont pas inclus : installez-les depuis la fenêtre principale.": "Firmware/BIOS sind nicht enthalten: Installieren Sie sie über das Hauptfenster.",
  "Les installations automatiques n’ont lieu que pendant cette plage.": "Automatische Installationen finden nur in diesem Zeitfenster statt.",
  "Les installations qui le nécessitent demanderont une élévation (UAC).": "Installationen, die es benötigen, fragen nach Erhöhung (UAC).",
  "Les noms et marques cités (Microsoft, Windows, NVIDIA, Intel, AMD, Lenovo, Dell, HP, ASUS…) appartiennent à leurs propriétaires. UpKeep n’est affilié à aucun d’eux.": "Die genannten Namen und Marken (Microsoft, Windows, NVIDIA, Intel, AMD, Lenovo, Dell, HP, ASUS…) gehören ihren Inhabern. UpKeep ist mit keinem von ihnen verbunden.",
  "Les paramètres de base ne sont pas modifiés.": "Die Basiseinstellungen werden nicht geändert.",
  "Licence": "Lizenz",
  "Lien de téléchargement inconnu : relancez une vérification.": "Unbekannter Download-Link: Führen Sie erneut eine Prüfung aus.",
  "Ligne de commande : upkeep-cli --check [--json] · --list · --install-all · --profile=<id>": "Kommandozeile: upkeep-cli --check [--json] · --list · --install-all · --profile=<id>",
  "Liste des logiciels et paquets": "Liste der Software und Pakete",
  "Liste des paquets": "Paketliste",
  "Logiciels installés": "Installierte Software",
  "Lun": "Mo",
  "Machine": "Computer",
  "Maintenance": "Wartung",
  "Mar": "Di",
  "Masquer les pilotes de périphériques absents": "Treiber für fehlende Geräte ausblenden",
  "Masquer les pilotes facultatifs de Windows Update": "Optionale Windows Update-Treiber ausblenden",
  "Masquer les préversions (bêta, RC…)": "Vorabversionen ausblenden (Beta, RC…)",
  "Masquées :": "Ausgeblendet:",
  "Matériel": "Hardware",
  "Mer": "Mi",
  "Mettez à jour les définitions (onglet Windows des mises à jour).": "Aktualisieren Sie die Definitionen (Registerkarte Windows der Updates).",
  "Mettre à jour": "Aktualisieren",
  "Mettre à jour automatiquement": "Automatisch aktualisieren",
  "Mettre à jour la sélection": "Auswahl aktualisieren",
  "Microsoft Store": "Microsoft Store",
  "Mise à jour automatique": "Automatisches Update",
  "Mise à jour de firmware/BIOS : branchez le chargeur secteur, fermez vos applications et n’interrompez pas le redémarrage.": "Firmware/BIOS-Update: Netzteil anschließen, Anwendungen schließen und den Neustart nicht unterbrechen.",
  "Mise à jour de fonctionnalités": "Funktionsupdate",
  "Mise à jour de sécurité": "Sicherheitsupdate",
  "Mise à jour de « {name} » lancée": "Update von „{name}“ gestartet",
  "Mise à jour terminée": "Update abgeschlossen",
  "Mise à jour urgente": "Dringendes Update",
  "Mises à jour": "Updates",
  "Mises à jour automatiques": "Automatische Updates",
  "Mises à jour cumulatives, Defender, .NET, Office et autres produits Microsoft": "Kumulative Updates, Defender, .NET, Office und andere Microsoft-Produkte",
  "Mises à jour de sécurité": "Sicherheitsupdates",
  "Mises à jour de sécurité disponibles": "Sicherheitsupdates verfügbar",
  "Mises à jour de sécurité en attente": "Ausstehende Sicherheitsupdates",
  "Mises à jour disponibles": "Verfügbare Updates",
  "Mises à jour ignorées": "Ignorierte Updates",
  "Mises à jour installées par mois": "Installierte Updates pro Monat",
  "Mo": "MB",
  "Mode simulation": "Simulationsmodus",
  "Mode simulation : rien ne sera installé.": "Simulationsmodus: Es wird nichts installiert.",
  "Modifier": "Bearbeiten",
  "Modifier un profil": "Profil bearbeiten",
  "Modifier…": "Ändern…",
  "Modules PowerShell installés avec Install-Module": "Mit Install-Module installierte PowerShell-Module",
  "Modèle": "Modell",
  "Mois": "Monat",
  "Monter": "Nach oben",
  "Motif": "Muster",
  "Mémoire": "Arbeitsspeicher",
  "Navigation": "Navigation",
  "Ne pas déranger": "Nicht stören",
  "Ne pas déranger en plein écran": "Im Vollbild nicht stören",
  "Ne pas déranger en plein écran, en jeu ou en mode Focus": "Nicht stören im Vollbild, in Spielen oder im Fokusmodus",
  "Ne pas notifier": "Nicht benachrichtigen",
  "Ne pas redémarrer": "Nicht neu starten",
  "Ne plus ignorer": "Nicht mehr ignorieren",
  "Nettoyage": "Bereinigung",
  "Nettoyer": "Bereinigen",
  "Nettoyer « {name} » ?": "„{name}“ bereinigen?",
  "Nom": "Name",
  "Nombre de sources interrogées en même temps (moins = moins de charge processeur).": "Anzahl gleichzeitig abgefragter Quellen (weniger = geringere CPU-Last).",
  "Non applicable à ce PC": "Für diesen PC nicht zutreffend",
  "Non suivis": "Nicht verfolgt",
  "Notes de version": "Versionshinweise",
  "Notification chaque lundi : installées, échecs, en attente.": "Benachrichtigung jeden Montag: installiert, fehlgeschlagen, ausstehend.",
  "Notifications": "Benachrichtigungen",
  "Notifications Windows": "Windows-Benachrichtigungen",
  "Nouveau": "Neu",
  "Nouveau profil": "Neues Profil",
  "Nouveautés depuis votre version ({v})": "Neuerungen seit Ihrer Version ({v})",
  "Nouvelle version annuelle de Windows (mise à jour de fonctionnalités)": "Neue jährliche Windows-Version (Funktionsupdate)",
  "Nouvelles mises à jour disponibles": "Neue Updates verfügbar",
  "Nouvelles mises à jour, fin des installations, rappels de redémarrage.": "Neue Updates, abgeschlossene Installationen, Neustart-Erinnerungen.",
  "Nécessaire pour la vérification périodique en arrière-plan.": "Erforderlich für die regelmäßige Prüfung im Hintergrund.",
  "Nécessite les droits administrateur.": "Erfordert Administratorrechte.",
  "Options winget": "winget-Optionen",
  "Oubli de périphérique": "Gerät entfernen",
  "Oublier": "Vergessen",
  "Oublier ce périphérique": "Dieses Gerät vergessen",
  "Oublier les périphériques absents ?": "Fehlende Geräte vergessen?",
  "Oublier tous": "Alle vergessen",
  "Outil": "Tool",
  "Outil de mise à jour": "Update-Tool",
  "Outil non installé": "Tool nicht installiert",
  "Outils installés avec « dotnet tool install -g »": "Mit „dotnet tool install -g“ installierte Tools",
  "Ouvrir": "Öffnen",
  "Ouvrir UpKeep": "UpKeep öffnen",
  "Ouvrir Intel DSA": "Intel DSA öffnen",
  "Ouvrir la page des pilotes AMD": "AMD-Treiberseite öffnen",
  "Ouvrir le dossier": "Ordner öffnen",
  "Ouvrir le dossier des téléchargements": "Download-Ordner öffnen",
  "Ouvrir le site": "Website öffnen",
  "Page": "Seite",
  "Page de téléchargement Intel ouverte dans le navigateur.": "Intel-Downloadseite im Browser geöffnet.",
  "Paquets": "Pakete",
  "Paquets Node.js en cache (npm les retélécharge au besoin).": "Zwischengespeicherte Node.js-Pakete (npm lädt sie bei Bedarf erneut herunter).",
  "Paquets Node.js installés avec « yarn global add »": "Mit „yarn global add“ installierte Node.js-Pakete",
  "Paquets Node.js installés globalement avec npm": "Global mit npm installierte Node.js-Pakete",
  "Paquets Node.js installés globalement avec pnpm": "Global mit pnpm installierte Node.js-Pakete",
  "Paquets Python de l’interpréteur par défaut": "Python-Pakete des Standardinterpreters",
  "Paquets Python en cache.": "Zwischengespeicherte Python-Pakete.",
  "Paquets apt / dnf / pacman / zypper des distributions WSL (démarre les distributions pour vérifier)": "apt / dnf / pacman / zypper-Pakete der WSL-Distributionen (startet die Distributionen zur Prüfung)",
  "Paquets installés avec « bun add -g »": "Mit „bun add -g“ installierte Pakete",
  "Paquets remplacés par une version plus récente dans le magasin de pilotes. Windows refuse de supprimer ceux encore utilisés.": "Pakete, die im Treiberspeicher durch eine neuere Version ersetzt wurden. Windows verweigert das Löschen noch verwendeter Pakete.",
  "Par défaut": "Standard",
  "Par source": "Nach Quelle",
  "Par type": "Nach Typ",
  "Paramètres": "Einstellungen",
  "Paramètres d’UpKeep": "UpKeep-Einstellungen",
  "Paramètres exportés.": "Einstellungen exportiert.",
  "Paramètres importés.": "Einstellungen importiert.",
  "Pare-feu Windows": "Windows-Firewall",
  "Partiel": "Teilweise",
  "Pas d’installation automatique en connexion limitée": "Keine automatische Installation bei getakteter Verbindung",
  "Pas d’installation automatique sur batterie sous": "Keine automatische Installation im Akkubetrieb unter",
  "Pas d’installeur Windows pour ce BIOS : mettez-le à jour depuis l’UEFI (EZ Flash).": "Kein Windows-Installer für dieses BIOS: Aktualisieren Sie es über UEFI (EZ Flash).",
  "Passer": "Überspringen",
  "Pastille du nombre de mises à jour sur l’icône de la barre des tâches": "Badge mit Anzahl der Updates auf dem Taskleistensymbol",
  "Pilote graphique Intel comparé à la dernière version publiée par Intel ; Intel DSA pour le Wi-Fi et le Bluetooth": "Intel-Grafiktreiber im Vergleich mit der neuesten Intel-Version; Intel DSA für WLAN und Bluetooth",
  "Pilotes": "Treiber",
  "Pilotes & firmware": "Treiber & Firmware",
  "Pilotes et firmwares (UEFI/BIOS, contrôleurs…) distribués par Windows Update": "Von Windows Update verteilte Treiber und Firmware (UEFI/BIOS, Controller…)",
  "Pilotes et installeurs téléchargés par UpKeep (NVIDIA, Dell, HP, ASUS, « Télécharger seulement »).": "Von UpKeep heruntergeladene Treiber und Installer (NVIDIA, Dell, HP, ASUS, „Nur herunterladen“).",
  "Pilotes non proposés : une stratégie de l’organisation les exclut de Windows Update (désactivez « Respecter les stratégies » pour passer outre).": "Keine Treiber angeboten: Eine Richtlinie der Organisation schließt sie von Windows Update aus (deaktivieren Sie „Richtlinien beachten“, um dies zu übergehen).",
  "Plage horaire": "Zeitfenster",
  "Planifier le redémarrage": "Neustart planen",
  "Plus d’actions": "Weitere Aktionen",
  "Plus tard": "Später",
  "Point de restauration avant pilotes, firmware et mises à jour Windows": "Wiederherstellungspunkt vor Treibern, Firmware und Windows-Updates",
  "Portée": "Bereich",
  "Pour les pilotes Wi-Fi et Bluetooth Intel, installez Intel DSA (action ci-dessous).": "Für Intel-WLAN- und Bluetooth-Treiber installieren Sie Intel DSA (Aktion unten).",
  "Problème": "Problem",
  "Processeur": "Prozessor",
  "Processus à fermer": "Zu schließender Prozess",
  "Prochaine vérification {when}": "Nächste Prüfung {when}",
  "Produit": "Produkt",
  "Profil": "Profil",
  "Profil : {name}": "Profil: {name}",
  "Profil actif": "Aktives Profil",
  "Profil activé à chaque démarrage d’UpKeep (ou via l’argument --profile=<id>).": "Profil, das bei jedem Start von UpKeep aktiviert wird (oder über das Argument --profile=<id>).",
  "Profil au lancement": "Startprofil",
  "Profils": "Profile",
  "Profils, règles, éléments ignorés, options par paquet…": "Profile, Regeln, ignorierte Elemente, Paketoptionen…",
  "Progression": "Fortschritt",
  "Proposée par Windows Update quand votre PC est éligible ; UpKeep ouvre Windows Update pour la lancer.": "Wird von Windows Update angeboten, wenn Ihr PC berechtigt ist; UpKeep öffnet Windows Update, um es zu starten.",
  "Précédent": "Zurück",
  "Prête": "Bereit",
  "Publiée le": "Veröffentlicht am",
  "Période": "Zeitraum",
  "Périphérique absent": "Fehlendes Gerät",
  "Périphériques absents mémorisés": "Gespeicherte fehlende Geräte",
  "Périphériques avec firmware": "Geräte mit Firmware",
  "Quarantaine des nouvelles versions": "Quarantäne für neue Versionen",
  "Quitter": "Beenden",
  "Raccourcis : Ctrl+R vérifier · Ctrl+F rechercher · Ctrl+A tout sélectionner · Entrée installer la sélection · Échap fermer": "Tastenkürzel: Strg+R prüfen · Strg+F suchen · Strg+A alles auswählen · Eingabe Auswahl installieren · Esc schließen",
  "Rappel de redémarrage": "Neustart-Erinnerung",
  "Rapport complet": "Vollständiger Bericht",
  "Rapport créé.": "Bericht erstellt.",
  "Rapport de diagnostic": "Diagnosebericht",
  "Rapport de sécurité": "Sicherheitsbericht",
  "Recharger l’interface": "Oberfläche neu laden",
  "Recherche en cours…": "Suche läuft…",
  "Recherche globale": "Globale Suche",
  "Recherche winget": "winget-Suche",
  "Rechercher": "Suchen",
  "Rechercher une page, une mise à jour, un réglage…": "Seite, Update oder Einstellung suchen…",
  "Rechercher…": "Suchen…",
  "Rechercher… (Ctrl+F)": "Suchen… (Strg+F)",
  "Recherche…": "Suche…",
  "Redémarrage": "Neustart",
  "Redémarrage automatique": "Automatischer Neustart",
  "Redémarrage automatique prévu à {time}, après vos heures d’activité.": "Automatischer Neustart um {time} geplant, nach Ihrer Nutzungszeit.",
  "Redémarrage en attente": "Neustart ausstehend",
  "Redémarrage planifié": "Neustart geplant",
  "Redémarrage planifié {when}": "Neustart geplant {when}",
  "Redémarrer automatiquement après mes heures d’activité": "Nach meiner Nutzungszeit automatisch neu starten",
  "Redémarrer dans": "Neu starten in",
  "Redémarrer maintenant": "Jetzt neu starten",
  "Redémarrer à": "Neu starten um",
  "Redémarrer…": "Neu starten…",
  "Relance de {path}": "{path} wird neu gestartet",
  "Relancer": "Erneut anzeigen",
  "Relancer après la mise à jour": "Nach dem Update neu starten",
  "Reporte notifications et installations automatiques.": "Verschiebt Benachrichtigungen und automatische Installationen.",
  "Respecter les stratégies de l’organisation": "Richtlinien der Organisation beachten",
  "Restauration de pilote": "Treiber-Wiederherstellung",
  "Restaurer le pilote": "Treiber zurücksetzen",
  "Restaurer le pilote précédent ?": "Vorherigen Treiber wiederherstellen?",
  "Rester dans la zone de notification à la fermeture": "Beim Schließen im Infobereich bleiben",
  "Rester sur la version majeure {major}": "Bei Hauptversion {major} bleiben",
  "Revenir à la version précédente ?": "Zur vorherigen Version zurückkehren?",
  "Revoir l’accueil": "Willkommen erneut anzeigen",
  "Rien à installer.": "Nichts zu installieren.",
  "Rythme et démarrage": "Rhythmus und Start",
  "Règles": "Regeln",
  "Réaffichage": "Einblenden",
  "Réafficher dans Windows Update": "In Windows Update wieder einblenden",
  "Réessayer": "Erneut versuchen",
  "Réessayer automatiquement après une erreur réseau": "Nach einem Netzwerkfehler automatisch erneut versuchen",
  "Réessayer une fois une source en échec": "Fehlgeschlagene Quelle einmal erneut versuchen",
  "Réglage": "Einstellung",
  "Réglages": "Einstellungen",
  "Réglages d’origine": "Auf Werkseinstellungen zurücksetzen",
  "Résultats": "Ergebnisse",
  "Résumé de la semaine": "Wochenübersicht",
  "Résumé hebdomadaire": "Wöchentliche Übersicht",
  "Réussi": "Erfolgreich",
  "SSD d’origine : firmware fourni par le constructeur du PC (voir Sources).": "Original-SSD: Firmware wird vom PC-Hersteller bereitgestellt (siehe Quellen).",
  "Sam": "Sa",
  "Sans chiffrement, les données sont lisibles si le PC est volé.": "Ohne Verschlüsselung sind die Daten bei Diebstahl des PCs lesbar.",
  "Santé": "Zustand",
  "Sauvegarde": "Sicherung",
  "Selon la source": "Wie Quelle",
  "Seul votre compte (et les administrateurs) peut y déposer des scripts. Cela revient à approuver d’avance les élévations de votre compte : un programme malveillant lancé sous votre session pourrait aussi s’en servir. Désactivez l’option pour supprimer la tâche.": "Nur Ihr Konto (und Administratoren) kann dort Skripte ablegen. Dies entspricht einer vorab erteilten Erhöhung für Ihr Konto: Schadsoftware in Ihrer Sitzung könnte sie ebenfalls nutzen. Deaktivieren Sie die Option, um die Aufgabe zu entfernen.",
  "Seules les sources détectées sur ce PC sont proposées. Vous pourrez changer d’avis dans « Sources ».": "Nur auf diesem PC erkannte Quellen werden angeboten. Sie können dies unter „Quellen“ ändern.",
  "Si un administrateur exclut les pilotes de Windows Update ou impose un serveur WSUS, UpKeep suit ces règles.": "Wenn ein Administrator Treiber von Windows Update ausschließt oder einen WSUS-Server vorgibt, folgt UpKeep diesen Regeln.",
  "Signature numérique invalide ou éditeur inattendu : installation bloquée.": "Ungültige digitale Signatur oder unerwarteter Herausgeber: Installation blockiert.",
  "Site": "Website",
  "Sombre": "Dunkel",
  "Source": "Quelle",
  "Source : endoflife.date. Un logiciel en fin de support ne reçoit plus de correctifs de sécurité.": "Quelle: endoflife.date. Software ohne Support erhält keine Sicherheitskorrekturen mehr.",
  "Sources": "Quellen",
  "Sources : Windows Update (classe Firmware) et l’outil constructeur s’il est configuré dans « Sources ».": "Quellen: Windows Update (Klasse Firmware) und das Herstellertool, falls unter „Quellen“ konfiguriert.",
  "Sources activées dans ce profil": "In diesem Profil aktivierte Quellen",
  "Sources différentes uniquement ; les installations administrateur sont regroupées.": "Nur verschiedene Quellen; Administratorinstallationen werden gebündelt.",
  "Sources d’alertes de sécurité": "Quellen für Sicherheitswarnungen",
  "Sources à surveiller": "Zu überwachende Quellen",
  "Sous-système Windows pour Linux (noyau et outils) comparé aux versions publiées sur GitHub": "Windows-Subsystem für Linux (Kernel und Tools) im Vergleich mit den auf GitHub veröffentlichten Versionen",
  "Statut": "Status",
  "Suivant": "Weiter",
  "Suivi par": "Verfolgt von",
  "Suivis": "Verfolgt",
  "Support {brand}": "{brand}-Support",
  "Supprimer": "Löschen",
  "Supprimer le profil « {name} » ?": "Profil „{name}“ löschen?",
  "Suspendre BitLocker pour un redémarrage avant un BIOS": "BitLocker vor einem BIOS-Update für einen Neustart anhalten",
  "Suspendre les notifications 4 h": "Benachrichtigungen 4 h pausieren",
  "Système": "System",
  "Sécurité": "Sicherheit",
  "Sécurité du poste": "PC-Sicherheit",
  "Sélectionner {name}": "{name} auswählen",
  "Tableau": "Tabelle",
  "Taille": "Größe",
  "Thème": "Design",
  "Total": "Gesamt",
  "Toujours automatique": "Immer automatisch",
  "Toujours bloquer sur batterie": "Im Akkubetrieb immer blockieren",
  "Toujours ignorer": "Immer ignorieren",
  "Tous les logiciels installés, et le gestionnaire qui les suit.": "Alle installierte Software und der Manager, der sie verfolgt.",
  "Tous les statuts": "Alle Status",
  "Tout": "Alle",
  "Tout est à jour": "Alles ist aktuell",
  "Tout est à jour.": "Alles ist aktuell.",
  "Tout installer": "Alle installieren",
  "Tout mettre à jour": "Alle aktualisieren",
  "Tout sélectionner": "Alle auswählen",
  "Toute la période": "Gesamter Zeitraum",
  "Toutes les sources": "Alle Quellen",
  "Toutes les sources activées, sauf réglage propre à une source.": "Alle aktivierten Quellen, sofern eine Quelle keine eigene Einstellung hat.",
  "Toutes les {n} h": "Alle {n} h",
  "Type": "Typ",
  "Tâche": "Aufgabe",
  "Tâche planifiée": "Geplante Aufgabe",
  "Téléchargement": "Download",
  "Téléchargement de {file}…": "{file} wird heruntergeladen…",
  "Téléchargement lancé": "Download gestartet",
  "Téléchargements d’UpKeep": "UpKeep-Downloads",
  "Téléchargements d’UpKeep supprimés.": "UpKeep-Downloads gelöscht.",
  "Télécharger": "Herunterladen",
  "Télécharger seulement": "Nur herunterladen",
  "Téléchargé : {path}": "Heruntergeladen: {path}",
  "Un point de restauration système sera créé avant l’installation.": "Vor der Installation wird ein Systemwiederherstellungspunkt erstellt.",
  "Un redémarrage est nécessaire pour finaliser certaines mises à jour.": "Ein Neustart ist erforderlich, um einige Updates abzuschließen.",
  "Un redémarrage sera nécessaire ensuite.": "Anschließend ist ein Neustart erforderlich.",
  "Une stratégie exclut les pilotes des mises à jour de qualité Windows Update.": "Eine Richtlinie schließt Treiber von den Qualitätsupdates von Windows Update aus.",
  "Une tâche planifiée système exécute les installations administrateur d’UpKeep. Nécessaire pour les mises à jour automatiques qui demandent l’administrateur.": "Eine geplante Systemaufgabe führt die Administratorinstallationen von UpKeep aus. Erforderlich für automatische Updates, die Administratorrechte benötigen.",
  "Une version n’est proposée qu’après ce délai depuis sa publication (ou sa première détection). Les mises à jour de sécurité ne sont jamais retenues.": "Eine Version wird erst nach Ablauf dieser Frist seit ihrer Veröffentlichung (oder ersten Erkennung) angeboten. Sicherheitsupdates werden nie zurückgehalten.",
  "Unité": "Einheit",
  "Utilisateur": "Benutzer",
  "Utilise les heures d’activité définies dans Windows Update.": "Verwendet die in Windows Update festgelegte Nutzungszeit.",
  "Utiliser la couleur d’accent de Windows": "Windows-Akzentfarbe verwenden",
  "Ven": "Fr",
  "Version": "Version",
  "Version après": "Version danach",
  "Version avant": "Version davor",
  "Version du pilote AMD Software: Adrenalin Edition installée": "Installierte Treiberversion von AMD Software: Adrenalin Edition",
  "Version installée : {v}. AMD ne publie pas d’API de versions et son site bloque les accès automatiques : utilisez « Rechercher les mises à jour » dans AMD Software.": "Installierte Version: {v}. AMD veröffentlicht keine Versions-API und seine Website blockiert automatisierte Zugriffe: Verwenden Sie „Nach Updates suchen“ in AMD Software.",
  "Version précise / retour arrière": "Bestimmte Version / Zurücksetzen",
  "Version précédente": "Vorherige Version",
  "Version {v}": "Version {v}",
  "Versions épinglées": "Fixierte Versionen",
  "Vider l’historique": "Verlauf leeren",
  "Voir les mises à jour": "Updates anzeigen",
  "Voir l’activité": "Aktivität anzeigen",
  "Vue compacte": "Kompakte Ansicht",
  "Vue compacte des listes": "Kompakte Listen",
  "Vérification en cours : {list}…": "Prüfung läuft: {list}…",
  "Vérification en cours…": "Prüfung läuft…",
  "Vérification périodique des mises à jour : paquets, Windows, pilotes, firmware et BIOS.": "Regelmäßige Prüfung auf Updates: Pakete, Windows, Treiber, Firmware und BIOS.",
  "Vérifications simultanées": "Gleichzeitige Prüfungen",
  "Vérification…": "Prüfung…",
  "Vérifier": "Prüfen",
  "Vérifier au démarrage de l’application": "Beim Start der Anwendung prüfen",
  "Vérifier au réveil de veille et au retour du réseau": "Beim Aufwachen aus dem Standby und bei Rückkehr des Netzwerks prüfen",
  "Vérifier maintenant": "Jetzt prüfen",
  "Vérifier même quand UpKeep est fermé": "Auch prüfen, wenn UpKeep geschlossen ist",
  "Vérifiez que vous avez votre clé de récupération BitLocker.": "Stellen Sie sicher, dass Sie Ihren BitLocker-Wiederherstellungsschlüssel haben.",
  "WSL : proposer les préversions": "WSL: Vorabversionen anbieten",
  "WinGet : inclure les paquets à version inconnue": "WinGet: Pakete mit unbekannter Version einbeziehen",
  "Windows": "Windows",
  "Windows Update est ouvert : cliquez sur « Télécharger et installer » si la version est proposée.": "Windows Update ist geöffnet: Klicken Sie auf „Herunterladen und installieren“, wenn die Version angeboten wird.",
  "Windows continue de proposer les pilotes des périphériques branchés un jour puis retirés. Les oublier supprime ces propositions.": "Windows bietet weiterhin Treiber für Geräte an, die einmal angeschlossen und dann entfernt wurden. Durch Vergessen verschwinden diese Angebote.",
  "Windows demandera une seule élévation (UAC) pour tout le lot.": "Windows fragt für den gesamten Stapel nur einmal nach Erhöhung (UAC).",
  "Windows mémorise tout périphérique déjà branché et continue de proposer ses pilotes.": "Windows merkt sich jedes jemals angeschlossene Gerät und bietet weiterhin seine Treiber an.",
  "Windows supprimera ces périphériques de sa mémoire. S’ils sont rebranchés, ils seront simplement redétectés.": "Windows entfernt diese Geräte aus seinem Speicher. Werden sie erneut angeschlossen, werden sie einfach wieder erkannt.",
  "Windows {family} version {v}": "Windows {family} Version {v}",
  "Zip local (journaux, rapports de plantage, paramètres) à joindre à un signalement. Rien n’est envoyé automatiquement.": "Lokales Zip (Protokolle, Absturzberichte, Einstellungen) zum Anhängen an eine Meldung. Es wird nichts automatisch gesendet.",
  "[simulation] aucune commande n’a été exécutée.": "[Simulation] Es wurde kein Befehl ausgeführt.",
  "[simulation] {type} via {provider} :": "[Simulation] {type} über {provider}:",
  "absent": "fehlt",
  "actif": "aktiv",
  "actif sur tous les profils": "in allen Profilen aktiv",
  "actif · définitions de {n} jour(s)": "aktiv · Definitionen {n} Tag(e) alt",
  "active": "aktiv",
  "activé": "aktiviert",
  "admin": "Admin",
  "afficher": "anzeigen",
  "aucun": "keine",
  "aujourd’hui à {time}": "heute um {time}",
  "aussi via {list}": "auch über {list}",
  "automatique": "automatisch",
  "batterie faible": "Akku schwach",
  "bientôt": "bald",
  "chiffrement en cours": "Verschlüsselung läuft",
  "connexion limitée": "getaktete Verbindung",
  "copie": "Kopie",
  "critique": "kritisch",
  "demain à {time}": "morgen um {time}",
  "désactivé": "deaktiviert",
  "désactivé pour : {list}": "deaktiviert für: {list}",
  "erreur": "Fehler",
  "et {n} autre(s)…": "und {n} weitere…",
  "exploitée": "ausgenutzt",
  "expérimental": "experimentell",
  "facultatif": "optional",
  "heures": "Stunden",
  "hors plage horaire": "außerhalb des Zeitfensters",
  "inconnu": "unbekannt",
  "inconnu (BIOS hérité ?)": "unbekannt (Legacy-BIOS?)",
  "inconnue": "unbekannt",
  "installé": "installiert",
  "installée": "installiert",
  "jamais": "nie",
  "je le ferai moi-même": "ich mache es selbst",
  "jours": "Tage",
  "les oublier": "sie vergessen",
  "maintenu": "unterstützt",
  "manuelle": "manuell",
  "masquée": "ausgeblendet",
  "masquée(s) dans Windows Update": "in Windows Update ausgeblendet",
  "minutes": "Minuten",
  "mode démo": "Demomodus",
  "nom du processus, ex. firefox": "Prozessname, z. B. firefox",
  "non annoncée": "nicht angekündigt",
  "non disponible": "nicht verfügbar",
  "non disponible (autre antivirus ?)": "nicht verfügbar (anderes Antivirenprogramm?)",
  "o": "B",
  "outil à installer": "Tool zu installieren",
  "par défaut ({n})": "Standard ({n})",
  "pilote(s) de périphériques absents": "Treiber für fehlende Geräte",
  "plein écran / ne pas déranger": "Vollbild / nicht stören",
  "portable": "portabel",
  "prochaine {when}": "nächste {when}",
  "présent · version {v}": "vorhanden · Version {v}",
  "préversion": "Vorabversion",
  "préversion(s)": "Vorabversion(en)",
  "quarantaine": "Quarantäne",
  "redémarrage": "Neustart",
  "reste sur la version {v}.x": "bleibt bei Version {v}.x",
  "simulation": "Simulation",
  "sur batterie": "im Akkubetrieb",
  "sur secteur": "am Netzteil",
  "suspendu": "angehalten",
  "sécurité": "Sicherheit",
  "tentative {n}": "Versuch {n}",
  "terminé": "beendet",
  "toujours ignorée": "immer ignoriert",
  "version {v} ignorée": "Version {v} ignoriert",
  "version(s) en quarantaine ({d} j)": "Version(en) in Quarantäne ({d} T)",
  "vide": "leer",
  "vérifié {when}": "geprüft {when}",
  "winget, Scoop, npm, pip, pipx, cargo, outils .NET et extensions VS Code. L’import réinstalle ce qui manque (suivi dans « Activité »).": "winget, Scoop, npm, pip, pipx, cargo, .NET-Tools und VS Code-Erweiterungen. Der Import installiert Fehlendes erneut (unter „Aktivität“ verfolgt).",
  "{name} installé": "{name} installiert",
  "{n} % de la capacité d’origine": "{n} % der ursprünglichen Kapazität",
  "{n} en cours": "{n} laufend",
  "{n} entrée(s)": "{n} Eintrag/Einträge",
  "{n} firmware/BIOS": "{n} Firmware/BIOS",
  "{n} h": "{n} h",
  "{n} heure(s)": "{n} Stunde(n)",
  "{n} j": "{n} T",
  "{n} jour(s)": "{n} Tag(e)",
  "{n} ligne(s) précédente(s)": "{n} vorherige Zeile(n)",
  "{n} min": "{n} min",
  "{n} minutes": "{n} Minuten",
  "{n} mise(s) à jour": "{n} Update(s)",
  "{n} mise(s) à jour Windows": "{n} Windows-Update(s)",
  "{n} mise(s) à jour corrigent une faille activement exploitée.": "{n} Update(s) beheben eine aktiv ausgenutzte Sicherheitslücke.",
  "{n} mise(s) à jour de sécurité à installer.": "{n} Sicherheitsupdate(s) zu installieren.",
  "{n} mise(s) à jour disponible(s)": "{n} Update(s) verfügbar",
  "{n} mise(s) à jour installée(s), {f} échec(s), {p} en attente, {q} en quarantaine.": "{n} Update(s) installiert, {f} fehlgeschlagen, {p} ausstehend, {q} in Quarantäne.",
  "{n} mise(s) à jour, aucune urgente.": "{n} Update(s), keines dringend.",
  "{n} mises à jour": "{n} Updates",
  "{n} mises à jour lancées": "{n} Updates gestartet",
  "{n} paquet(s)": "{n} Paket(e)",
  "{n} pilote(s)": "{n} Treiber",
  "{n} pilote(s) proposés": "{n} Treiber angeboten",
  "{n} source(s) actives sur {total}.": "{n} von {total} Quelle(n) aktiv.",
  "{n} sélectionné(s)": "{n} ausgewählt",
  "{n} élément(s)": "{n} Element(e)",
  "{p} : fin de support le {d}": "{p}: Supportende am {d}",
  "{p} n’est plus maintenu": "{p} wird nicht mehr unterstützt",
  "{s} s": "{s} s",
  "« {name} » ignorée": "„{name}“ ignoriert",
  "À propos": "Über",
  "À surveiller": "Beobachten",
  "Échec": "Fehlgeschlagen",
  "Échec de la mise à jour": "Update fehlgeschlagen",
  "Échec, nouvelle tentative dans 5 s": "Fehlgeschlagen, neuer Versuch in 5 s",
  "Échecs": "Fehlschläge",
  "Éditeur": "Herausgeber",
  "Élément": "Element",
  "État": "Status",
  "État avant la mise à jour": "Status vor dem Update",
  "État du poste": "PC-Status",
  "Évite de devoir saisir la clé de récupération après la mise à jour du firmware.": "Vermeidet die Eingabe des Wiederherstellungsschlüssels nach dem Firmware-Update.",
  "Pour : {name}": "Für: {name}",
  "Périphérique absent : {name}": "Fehlendes Gerät: {name}",
  "démo": "Demo",
  "Licence : PolyForm Noncommercial 1.0.0. Toute utilisation commerciale nécessite une licence commerciale.": "Lizenz: PolyForm Noncommercial 1.0.0. Jede kommerzielle Nutzung erfordert eine kommerzielle Lizenz.",
};
