export const EN: Record<string, string> = {
  ' — redémarrage requis': ' — restart required',
  '(aucune sortie pour le moment)': '(no output yet)',
  '(indisponible)': '(unavailable)',
  '(vide)': '(empty)',
  '1 jour': '1 day',
  '1 semaine': '1 week',
  '30 derniers jours': 'Last 30 days',
  '7 derniers jours': 'Last 7 days',
  '90 derniers jours': 'Last 90 days',
  'Accueil': 'Home',
  'Action': 'Action',
  'Actions': 'Actions',
  'Activer': 'Enable',
  'Activer l’assistant administrateur ?': 'Enable the administrator helper?',
  'Activité': 'Activity',
  'Activé': 'Enabled',
  'Actualiser': 'Refresh',
  'Afficher les mises à jour masquées dans Windows Update': 'Show updates hidden in Windows Update',
  'Afficher quand même les versions en quarantaine': 'Show quarantined versions anyway',
  'Ajouter une règle': 'Add a rule',
  'Annuler': 'Cancel',
  'Annuler le redémarrage': 'Cancel restart',
  'Annulé': 'Cancelled',
  'Apparence': 'Appearance',
  'Application à fermer': 'App to close',
  'Applications': 'Applications',
  'Applications Python isolées installées avec pipx': 'Isolated Python apps installed with pipx',
  'Applications du Microsoft Store (via winget, source msstore)': 'Microsoft Store apps (via winget, msstore source)',
  'Applique ses réglages par-dessus les paramètres. Aussi accessible depuis la zone de notification.':
    'Applies its overrides on top of the settings. Also available from the notification area.',
  'Architecture': 'Architecture',
  'Arguments supplémentaires pour l’installeur': 'Extra installer arguments',
  'Assistant administrateur': 'Administrator helper',
  'Associer': 'Link',
  'Associer « {name} » à un paquet winget': 'Link “{name}” to a winget package',
  'Au démarrage, une source vérifiée plus récemment que ce délai n’est pas réinterrogée.':
    'On startup, sources checked more recently than this are not queried again.',
  'Aucun': 'None',
  'Aucun outil connu': 'No known tool',
  'Aucun paquet trouvé.': 'No package found.',
  'Aucun pilote Studio publié pour ce GPU : UpKeep propose la branche Game Ready.':
    'No Studio driver is published for this GPU: UpKeep offers the Game Ready branch.',
  'Aucun périphérique Logitech, Razer, SteelSeries ou Corsair connecté.': 'No Logitech, Razer, SteelSeries or Corsair device connected.',
  'Aucun résultat.': 'No results.',
  'Aucune activité.': 'No activity.',
  'Aucune règle.': 'No rules.',
  'Aucune.': 'None.',
  'UpKeep surveille les mises à jour de vos logiciels, de Windows, de vos pilotes et de votre BIOS, et les installe quand vous le décidez.':
    'UpKeep watches for updates to your software, Windows, drivers and BIOS, and installs them when you decide.',
  'UpKeep tourne avec les droits administrateur.': 'UpKeep is running with administrator rights.',
  'UpKeep — vérification en cours…': 'UpKeep — checking…',
  'UpKeep — {n} mise(s) à jour disponible(s)': 'UpKeep — {n} update(s) available',
  'Automatiques en pause : {why}': 'Automatic updates paused: {why}',
  'Automatisation': 'Automation',
  'BIOS installé :': 'Installed BIOS:',
  'BIOS publié sur le site de support ASUS pour votre modèle': 'BIOS published on the ASUS support site for your model',
  'BIOS, firmware et pilotes Dell via dcu-cli': 'Dell BIOS, firmware and drivers via dcu-cli',
  'BIOS, firmware et pilotes HP analysés par HP Image Assistant': 'HP BIOS, firmware and drivers analysed by HP Image Assistant',
  'Batterie': 'Battery',
  'Batterie : {n} %': 'Battery: {n}%',
  'Batterie minimale pour un firmware/BIOS': 'Minimum battery for firmware/BIOS',
  'Bienvenue dans UpKeep': 'Welcome to UpKeep',
  'Binaires Rust installés avec « cargo install »': 'Rust binaries installed with “cargo install”',
  'BitLocker sera suspendu pour un redémarrage.': 'BitLocker will be suspended for one restart.',
  'Bloquer en connexion limitée': 'Block on metered connections',
  'Branche des pilotes NVIDIA': 'NVIDIA driver branch',
  'Cache des résultats': 'Result cache',
  'Carte mère': 'Motherboard',
  'Cartes graphiques': 'Graphics cards',
  'Catalogue constructeur Lenovo via le module PowerShell LSUClient': 'Lenovo catalog via the LSUClient PowerShell module',
  'Ce PC est configuré pour un serveur WSUS ({srv}) ; UpKeep interroge tout de même Windows Update directement.':
    'This PC is configured for a WSUS server ({srv}); UpKeep still queries Windows Update directly.',
  'Ce PC est géré par une organisation (Intune / MDM) : certaines mises à jour peuvent être bloquées par stratégie.':
    'This PC is managed by an organization (Intune / MDM): some updates may be blocked by policy.',
  'Ces applications seront fermées avant la mise à jour : {list}': 'These apps will be closed before updating: {list}',
  'Ces programmes ne sont suivis par aucun gestionnaire. Associez-les à un paquet winget pour qu’UpKeep surveille leurs mises à jour.':
    'These programs are not tracked by any package manager. Link them to a winget package so UpKeep watches their updates.',
  'Champ': 'Field',
  'Charge': 'Charge',
  'Charger les versions': 'Load versions',
  'Chargement des détails…': 'Loading details…',
  'Chargement…': 'Loading…',
  'Choisir': 'Choose',
  'Choisir…': 'Choose…',
  'Chrome, Edge et Firefox comparés à la dernière version stable publiée': 'Chrome, Edge and Firefox compared with the latest stable release',
  'Clair': 'Light',
  'Comme les paramètres': 'Same as settings',
  'Commencer': 'Get started',
  'Composants, firmwares et outils constructeur.': 'Components, firmware and vendor tools.',
  'Confirmer': 'Confirm',
  'Confirmer le téléchargement': 'Confirm download',
  'Confirmer l’installation': 'Confirm installation',
  'Connexion limitée': 'Metered connection',
  'Copier': 'Copy',
  'Copier le journal': 'Copy log',
  'Copier l’identifiant': 'Copy ID',
  'Copié !': 'Copied!',
  'Crée une tâche planifiée Windows (sans droits administrateur) qui lance une vérification à la fréquence choisie.':
    'Creates a Windows scheduled task (no admin rights) that runs a check at the chosen frequency.',
  'Date': 'Date',
  'Dernier pilote Game Ready ou Studio publié par NVIDIA pour votre carte graphique': 'Latest Game Ready or Studio driver published by NVIDIA for your graphics card',
  'Dernière vérification : {last} · prochaine {next}': 'Last check: {last} · next {next}',
  'Des mises à jour attendent un redémarrage pour être finalisées.': 'Some updates are waiting for a restart to finish.',
  'Descendre': 'Move down',
  'Description': 'Description',
  'Dim': 'Sun',
  'Disponible': 'Available',
  'Disques et firmware': 'Disks and firmware',
  'Dissocier ({id})': 'Unlink ({id})',
  'Docker n’est pas démarré : les images ne peuvent pas être vérifiées.': 'Docker is not running: images cannot be checked.',
  'Dossier des téléchargements': 'Downloads folder',
  'Dupliquer': 'Duplicate',
  'Durée': 'Duration',
  'Début': 'Start',
  'Délai max (min)': 'Timeout (min)',
  'Démarre réduit dans la zone de notification (version installée uniquement).': 'Starts minimized to the notification area (installed version only).',
  'Démarrer masqué': 'Start hidden',
  'Désactiver': 'Disable',
  'Désactivé': 'Disabled',
  'Désactivée': 'Disabled',
  'Désépingler': 'Unpin',
  'Détails': 'Details',
  'Développement': 'Development',
  'En attente': 'Queued',
  'En cours': 'Running',
  'En cours…': 'Running…',
  'En pause actuellement : {why}': 'Currently paused: {why}',
  'En quarantaine jusqu’au {date} (version récente).': 'Quarantined until {date} (recent release).',
  'Enregistrez votre travail : Windows redémarre immédiatement.': 'Save your work: Windows restarts immediately.',
  'Entrée': 'Enter',
  'Erreur': 'Error',
  'Exiger le secteur pour un firmware/BIOS': 'Require AC power for firmware/BIOS',
  'Export / import': 'Export / import',
  'Export annulé.': 'Export cancelled.',
  'Export lancé (voir Activité).': 'Export started (see Activity).',
  'Exporter': 'Export',
  'Exporter en CSV': 'Export to CSV',
  'Exporté vers {path}': 'Exported to {path}',
  'Extensions Visual Studio Code dont une version plus récente existe sur le Marketplace': 'Visual Studio Code extensions with a newer version on the Marketplace',
  'Fermer': 'Close',
  'Fichier de paramètres UpKeep invalide.': 'Invalid UpKeep settings file.',
  'Filtres': 'Filters',
  'Fin': 'End',
  'Firmware': 'Firmware',
  'Firmware & BIOS': 'Firmware & BIOS',
  'Forfait mobile, partage de connexion…': 'Mobile data, tethering…',
  'Fréquence': 'Frequency',
  'Fréquence de vérification': 'Check frequency',
  'Fréquence globale': 'Global frequency',
  'Gestionnaire de paquets Chocolatey (nécessite les droits administrateur)': 'Chocolatey package manager (requires admin rights)',
  'Gestionnaire de paquets Windows (Microsoft)': 'Windows Package Manager (Microsoft)',
  'Gestionnaires de paquets, Windows Update, pilotes graphiques et outils constructeur.': 'Package managers, Windows Update, graphics drivers and vendor tools.',
  'Go': 'GB',
  'Graphique': 'Chart',
  'Graphique en barres empilées': 'Stacked bar chart',
  'Grouper': 'Group',
  'Général': 'General',
  'Heure': 'Time',
  'Identifiant': 'ID',
  'Ignorer cette version': 'Ignore this version',
  'Ignorées & épinglées': 'Ignored & pinned',
  'Images locales dont une version plus récente est publiée sur Docker Hub': 'Local images with a newer build published on Docker Hub',
  'Import lancé (voir Activité).': 'Import started (see Activity).',
  'Importer': 'Import',
  'Infos': 'Info',
  'Installateur en ligne de commande pour Windows': 'Command-line installer for Windows',
  'Installation': 'Installation',
  'Installation impossible': 'Cannot install',
  'Installation via l’assistant administrateur (sans fenêtre UAC).': 'Installed through the administrator helper (no UAC prompt).',
  'Installations en cours, file d’attente et historique.': 'Running installations, queue and history.',
  'Installations en parallèle': 'Parallel installations',
  'Installe sans intervention les mises à jour des sources et paquets marqués « automatique » (Sources › Réglages, ou panneau de détail).':
    'Installs updates from sources and packages marked “automatic” without intervention (Sources › Settings, or the detail panel).',
  'Installer (une fenêtre UAC)': 'Install (one UAC prompt)',
  'Installer Dell Command | Update (winget)': 'Install Dell Command | Update (winget)',
  'Installer HP Image Assistant (winget)': 'Install HP Image Assistant (winget)',
  'Installer Intel DSA (winget)': 'Install Intel DSA (winget)',
  'Installer ces mises à jour ? (o/N) ': 'Install these updates? (y/N) ',
  'Installer cette version': 'Install this version',
  'Installer le module LSUClient': 'Install the LSUClient module',
  'Installer le module Microsoft.WinGet.Client': 'Install the Microsoft.WinGet.Client module',
  'Installer sans fenêtre UAC': 'Install without UAC prompts',
  'Installer une version précise': 'Install a specific version',
  'Installer {n} élément(s)': 'Install {n} item(s)',
  'Installé le': 'Installed on',
  'Installée': 'Installed',
  'Interrompre': 'Stop',
  'Inventaire': 'Inventory',
  'Jamais': 'Never',
  'Jamais automatique': 'Never automatic',
  'Jamais automatiquement': 'Never automatically',
  'Jamais bloquer': 'Never block',
  'Jeu': 'Thu',
  'Jokers : * = n’importe quelle suite, ? = un caractère. Exemples : *.Preview, Microsoft.*, *chrome*.':
    'Wildcards: * = any sequence, ? = one character. Examples: *.Preview, Microsoft.*, *chrome*.',
  'Journal': 'Log',
  'Journal de diagnostic — {name}': 'Diagnostic log — {name}',
  'Journal des modifications': 'Changelog',
  'Jours': 'Days',
  'Ko': 'KB',
  'Lancer avec Windows': 'Start with Windows',
  'Lancer avec Windows (réduit dans la zone de notification)': 'Start with Windows (minimized to the notification area)',
  'Langue': 'Language',
  'Langue de Windows': 'Windows language',
  'Le firmware de ces périphériques se met à jour depuis le logiciel du fabricant.': 'These devices’ firmware is updated from the manufacturer’s software.',
  'Le pilote installé pour « {name} » sera retiré du magasin de pilotes ; Windows reviendra à la version précédente. Un redémarrage peut être nécessaire.':
    'The driver installed for “{name}” will be removed from the driver store; Windows will fall back to the previous version. A restart may be needed.',
  'Lecture des programmes installés…': 'Reading installed programs…',
  'Lecture du matériel…': 'Reading hardware…',
  'Les firmwares/BIOS ne sont pas inclus : installez-les depuis la fenêtre principale.': 'Firmware/BIOS updates are not included: install them from the main window.',
  'Les installations automatiques n’ont lieu que pendant cette plage.': 'Automatic installs only happen during this window.',
  'Les installations qui le nécessitent demanderont une élévation (UAC).': 'Installations that need it will ask for elevation (UAC).',
  'Les paramètres de base ne sont pas modifiés.': 'Base settings are not changed.',
  'Licence': 'License',
  'Ligne de commande : upkeep-cli --check [--json] · --list · --install-all · --profile=<id>':
    'Command line: upkeep-cli --check [--json] · --list · --install-all · --profile=<id>',
  'Liste des logiciels et paquets': 'Software and package list',
  'Liste des paquets': 'Package list',
  'Logiciels installés': 'Installed software',
  'Lun': 'Mon',
  'Machine': 'Machine',
  'Mar': 'Tue',
  'Masquer les pilotes de périphériques absents': 'Hide drivers for absent devices',
  'Masquer les préversions (bêta, RC…)': 'Hide pre-releases (beta, RC…)',
  'Masquées :': 'Hidden:',
  'Matériel': 'Hardware',
  'Mer': 'Wed',
  'Mettre à jour': 'Update',
  'Mettre à jour automatiquement': 'Update automatically',
  'Mettre à jour la sélection': 'Update selection',
  'Microsoft Store': 'Microsoft Store',
  'Mise à jour automatique': 'Automatic update',
  'Mise à jour de firmware/BIOS : branchez le chargeur secteur, fermez vos applications et n’interrompez pas le redémarrage.':
    'Firmware/BIOS update: plug in the charger, close your apps and do not interrupt the restart.',
  'Mise à jour de sécurité': 'Security update',
  'Mise à jour de « {name} » lancée': 'Update of “{name}” started',
  'Mise à jour terminée': 'Update finished',
  'Mises à jour': 'Updates',
  'Mises à jour automatiques': 'Automatic updates',
  'Mises à jour cumulatives, Defender, .NET, Office et autres produits Microsoft': 'Cumulative updates, Defender, .NET, Office and other Microsoft products',
  'Mises à jour de sécurité disponibles': 'Security updates available',
  'Mises à jour disponibles': 'Available updates',
  'Mises à jour ignorées': 'Ignored updates',
  'Mises à jour installées par mois': 'Updates installed per month',
  'Mo': 'MB',
  'Modifier': 'Edit',
  'Modifier un profil': 'Edit a profile',
  'Modifier…': 'Change…',
  'Modules PowerShell installés avec Install-Module': 'PowerShell modules installed with Install-Module',
  'Modèle': 'Model',
  'Mois': 'Month',
  'Monter': 'Move up',
  'Motif': 'Pattern',
  'Mémoire': 'Memory',
  'Navigation': 'Navigation',
  'Ne pas déranger': 'Do not disturb',
  'Ne pas déranger en plein écran': 'Do not disturb in full screen',
  'Ne pas déranger en plein écran, en jeu ou en mode Focus': 'Do not disturb in full screen, games or Focus mode',
  'Ne pas notifier': 'Do not notify',
  'Ne pas redémarrer': 'Don’t restart',
  'Ne plus ignorer': 'Stop ignoring',
  'Nom': 'Name',
  'Non applicable à ce PC': 'Not applicable to this PC',
  'Non suivis': 'Untracked',
  'Notes de version': 'Release notes',
  'Notifications': 'Notifications',
  'Notifications Windows': 'Windows notifications',
  'Nouveau': 'New',
  'Nouveau profil': 'New profile',
  'Nouvelles mises à jour disponibles': 'New updates available',
  'Nouvelles mises à jour, fin des installations, rappels de redémarrage.': 'New updates, finished installs, restart reminders.',
  'Nécessaire pour la vérification périodique en arrière-plan.': 'Required for periodic background checks.',
  'Options winget': 'winget options',
  'Outil': 'Tool',
  'Outil de mise à jour': 'Update tool',
  'Outil non installé': 'Tool not installed',
  'Outils installés avec « dotnet tool install -g »': 'Tools installed with “dotnet tool install -g”',
  'Ouvrir': 'Open',
  'Ouvrir UpKeep': 'Open UpKeep',
  'Ouvrir Intel DSA': 'Open Intel DSA',
  'Ouvrir la page des pilotes AMD': 'Open the AMD drivers page',
  'Ouvrir le dossier des téléchargements': 'Open downloads folder',
  'Ouvrir le site': 'Open website',
  'Paquets': 'Packages',
  'Paquets Node.js installés avec « yarn global add »': 'Node.js packages installed with “yarn global add”',
  'Paquets Node.js installés globalement avec npm': 'Node.js packages installed globally with npm',
  'Paquets Node.js installés globalement avec pnpm': 'Node.js packages installed globally with pnpm',
  'Paquets Python de l’interpréteur par défaut': 'Python packages of the default interpreter',
  'Paquets apt / dnf / pacman / zypper des distributions WSL (démarre les distributions pour vérifier)':
    'apt / dnf / pacman / zypper packages of WSL distributions (starts the distributions to check)',
  'Paquets installés avec « bun add -g »': 'Packages installed with “bun add -g”',
  'Par défaut': 'Default',
  'Par source': 'By source',
  'Par type': 'By type',
  'Paramètres': 'Settings',
  'Paramètres d’UpKeep': 'UpKeep settings',
  'Paramètres exportés.': 'Settings exported.',
  'Paramètres importés.': 'Settings imported.',
  'Partiel': 'Partial',
  'Pas d’installation automatique en connexion limitée': 'No automatic installs on metered connections',
  'Pas d’installation automatique sur batterie sous': 'No automatic installs on battery below',
  'Passer': 'Skip',
  'Pastille du nombre de mises à jour sur l’icône de la barre des tâches': 'Update count badge on the taskbar icon',
  'Pilotes': 'Drivers',
  'Pilotes & firmware': 'Drivers & firmware',
  'Pilotes Intel (graphique, Wi-Fi, Bluetooth) souvent plus récents que ceux de Windows Update': 'Intel drivers (graphics, Wi-Fi, Bluetooth), often newer than Windows Update’s',
  'Pilotes et firmwares (UEFI/BIOS, contrôleurs…) distribués par Windows Update': 'Drivers and firmware (UEFI/BIOS, controllers…) distributed by Windows Update',
  'Plage horaire': 'Time window',
  'Planifier le redémarrage': 'Schedule restart',
  'Plus d’actions': 'More actions',
  'Point de restauration avant pilotes, firmware et mises à jour Windows': 'Restore point before drivers, firmware and Windows updates',
  'Portée': 'Scope',
  'Processeur': 'Processor',
  'Processus à fermer': 'Process to close',
  'Prochaine vérification {when}': 'Next check {when}',
  'Profil': 'Profile',
  'Profil : {name}': 'Profile: {name}',
  'Profil activé à chaque démarrage d’UpKeep (ou via l’argument --profile=<id>).': 'Profile enabled each time UpKeep starts (or via the --profile=<id> argument).',
  'Profil actif': 'Active profile',
  'Profil au lancement': 'Startup profile',
  'Profils': 'Profiles',
  'Profils, règles, éléments ignorés, options par paquet…': 'Profiles, rules, ignored items, per-package options…',
  'Progression': 'Progress',
  'Précédent': 'Back',
  'Prête': 'Ready',
  'Publiée le': 'Published',
  'Période': 'Period',
  'Périphériques avec firmware': 'Devices with firmware',
  'Quarantaine des nouvelles versions': 'New release quarantine',
  'Quitter': 'Quit',
  'Raccourcis : Ctrl+R vérifier · Ctrl+F rechercher · Ctrl+A tout sélectionner · Entrée installer la sélection · Échap fermer':
    'Shortcuts: Ctrl+R check · Ctrl+F search · Ctrl+A select all · Enter install selection · Esc close',
  'Rappel de redémarrage': 'Restart reminder',
  'Recherche en cours…': 'Searching…',
  'Recherche winget': 'winget search',
  'Rechercher': 'Search',
  'Rechercher…': 'Search…',
  'Rechercher… (Ctrl+F)': 'Search… (Ctrl+F)',
  'Recherche…': 'Searching…',
  'Redémarrage': 'Restart',
  'Redémarrage automatique': 'Automatic restart',
  'Redémarrage automatique prévu à {time}, après vos heures d’activité.': 'Automatic restart scheduled at {time}, after your active hours.',
  'Redémarrage en attente': 'Restart pending',
  'Redémarrage planifié': 'Restart scheduled',
  'Redémarrage planifié {when}': 'Restart scheduled {when}',
  'Redémarrer automatiquement après mes heures d’activité': 'Restart automatically after my active hours',
  'Redémarrer dans': 'Restart in',
  'Redémarrer maintenant': 'Restart now',
  'Redémarrer à': 'Restart at',
  'Redémarrer…': 'Restart…',
  'Relancer': 'Show again',
  'Relancer après la mise à jour': 'Relaunch after updating',
  'Reporte notifications et installations automatiques.': 'Postpones notifications and automatic installs.',
  'Restauration de pilote': 'Driver rollback',
  'Restaurer le pilote': 'Roll back driver',
  'Restaurer le pilote précédent ?': 'Roll back to the previous driver?',
  'Rester dans la zone de notification à la fermeture': 'Stay in the notification area when closed',
  'Rester sur la version majeure {major}': 'Stay on major version {major}',
  'Revenir à la version précédente ?': 'Go back to the previous version?',
  'Revoir l’accueil': 'Show welcome again',
  'Rien à installer.': 'Nothing to install.',
  'Rythme et démarrage': 'Schedule and startup',
  'Règles': 'Rules',
  'Réaffichage': 'Unhide',
  'Réafficher dans Windows Update': 'Unhide in Windows Update',
  'Réessayer automatiquement après une erreur réseau': 'Retry automatically after a network error',
  'Réessayer une fois une source en échec': 'Retry a failed source once',
  'Réglages': 'Settings',
  'Réglages d’origine': 'Reset to original',
  'Réussi': 'Succeeded',
  'SSD d’origine : firmware fourni par le constructeur du PC (voir Sources).': 'Factory SSD: firmware is provided by the PC manufacturer (see Sources).',
  'Sam': 'Sat',
  'Santé': 'Health',
  'Sauvegarde': 'Backup',
  'Selon la source': 'Same as source',
  'Seul votre compte (et les administrateurs) peut y déposer des scripts. Cela revient à approuver d’avance les élévations de votre compte : un programme malveillant lancé sous votre session pourrait aussi s’en servir. Désactivez l’option pour supprimer la tâche.':
    'Only your account (and administrators) can drop scripts there. This amounts to pre-approving elevations for your account: malware running in your session could use it too. Turn the option off to remove the task.',
  'Seules les sources détectées sur ce PC sont proposées. Vous pourrez changer d’avis dans « Sources ».':
    'Only sources detected on this PC are listed. You can change your mind in “Sources”.',
  'Site': 'Website',
  'Sombre': 'Dark',
  'Source': 'Source',
  'Sources': 'Sources',
  'Sources : Windows Update (classe Firmware) et l’outil constructeur s’il est configuré dans « Sources ».':
    'Sources: Windows Update (Firmware class) and the vendor tool if configured in “Sources”.',
  'Sources activées dans ce profil': 'Sources enabled in this profile',
  'Sources différentes uniquement ; les installations administrateur sont regroupées.': 'Different sources only; administrator installs are batched.',
  'Sources à surveiller': 'Sources to watch',
  'Sous-système Windows pour Linux (noyau et outils) comparé aux versions publiées sur GitHub': 'Windows Subsystem for Linux (kernel and tools) compared with releases on GitHub',
  'Statut': 'Status',
  'Suivant': 'Next',
  'Suivi par': 'Tracked by',
  'Suivis': 'Tracked',
  'Support {brand}': '{brand} support',
  'Supprimer': 'Delete',
  'Supprimer le profil « {name} » ?': 'Delete profile “{name}”?',
  'Suspendre BitLocker pour un redémarrage avant un BIOS': 'Suspend BitLocker for one restart before a BIOS update',
  'Système': 'System',
  'Sélectionner {name}': 'Select {name}',
  'Tableau': 'Table',
  'Taille': 'Size',
  'Thème': 'Theme',
  'Total': 'Total',
  'Toujours automatique': 'Always automatic',
  'Toujours bloquer sur batterie': 'Always block on battery',
  'Toujours ignorer': 'Always ignore',
  'Tous les logiciels installés, et le gestionnaire qui les suit.': 'All installed software, and the manager that tracks it.',
  'Tous les statuts': 'All statuses',
  'Tout': 'All',
  'Tout est à jour.': 'Everything is up to date.',
  'Tout installer': 'Install all',
  'Tout mettre à jour': 'Update all',
  'Tout sélectionner': 'Select all',
  'Toute la période': 'All time',
  'Toutes les sources': 'All sources',
  'Toutes les sources activées, sauf réglage propre à une source.': 'All enabled sources, unless a source has its own setting.',
  'Toutes les {n} h': 'Every {n} h',
  'Type': 'Type',
  'Tâche': 'Task',
  'Tâche planifiée': 'Scheduled task',
  'Téléchargement': 'Download',
  'Téléchargement lancé': 'Download started',
  'Télécharger': 'Download',
  'Télécharger seulement': 'Download only',
  'Un point de restauration système sera créé avant l’installation.': 'A system restore point will be created before installing.',
  'Un redémarrage est nécessaire pour finaliser certaines mises à jour.': 'A restart is needed to finish some updates.',
  'Un redémarrage sera nécessaire ensuite.': 'A restart will be needed afterwards.',
  'Une stratégie exclut les pilotes de Windows Update.': 'A policy excludes drivers from Windows Update.',
  'Une stratégie exclut les pilotes des mises à jour de qualité Windows Update.': 'A policy excludes drivers from Windows Update quality updates.',
  'Une tâche planifiée système exécute les installations administrateur d’UpKeep. Nécessaire pour les mises à jour automatiques qui demandent l’administrateur.':
    'A system scheduled task runs UpKeep’s administrator installs. Required for automatic updates that need administrator rights.',
  'Une tâche planifiée « UpKeep\\ElevatedHelper » sera créée. Elle tourne avec les droits SYSTÈME et exécute les scripts déposés par UpKeep dans C:\\ProgramData\\UpKeep\\queue.':
    'A scheduled task “UpKeep\\ElevatedHelper” will be created. It runs as SYSTEM and executes the scripts UpKeep drops into C:\\ProgramData\\UpKeep\\queue.',
  'Une version n’est proposée qu’après ce délai depuis sa publication (ou sa première détection). Les mises à jour de sécurité ne sont jamais retenues.':
    'A version is only offered once this delay has passed since its release (or first detection). Security updates are never held back.',
  'Unité': 'Unit',
  'Utilisateur': 'User',
  'Utilise les heures d’activité définies dans Windows Update.': 'Uses the active hours set in Windows Update.',
  'Utiliser la couleur d’accent de Windows': 'Use the Windows accent color',
  'Ven': 'Fri',
  'Version': 'Version',
  'Version du pilote AMD Software: Adrenalin Edition installée': 'Installed AMD Software: Adrenalin Edition driver version',
  'Version précise / retour arrière': 'Specific version / rollback',
  'Version précédente': 'Previous version',
  'Version {v}': 'Version {v}',
  'Versions épinglées': 'Pinned versions',
  'Vider l’historique': 'Clear history',
  'Voir l’activité': 'View activity',
  'Vérification en cours : {list}…': 'Checking: {list}…',
  'Vérification périodique des mises à jour : paquets, Windows, pilotes, firmware et BIOS.': 'Periodic update checks: packages, Windows, drivers, firmware and BIOS.',
  'Vérification…': 'Checking…',
  'Vérifier': 'Check',
  'Vérifier au démarrage de l’application': 'Check when the app starts',
  'Vérifier au réveil de veille et au retour du réseau': 'Check on wake from sleep and when the network returns',
  'Vérifier maintenant': 'Check now',
  'Vérifier même quand UpKeep est fermé': 'Check even when UpKeep is closed',
  'Vérifiez que vous avez votre clé de récupération BitLocker.': 'Make sure you have your BitLocker recovery key.',
  'WSL : proposer les préversions': 'WSL: offer pre-releases',
  'WinGet : inclure les paquets à version inconnue': 'WinGet: include packages with unknown versions',
  'Windows': 'Windows',
  'Windows demandera une seule élévation (UAC) pour tout le lot.': 'Windows will ask for a single elevation (UAC) for the whole batch.',
  'Windows mémorise tout périphérique déjà branché et continue de proposer ses pilotes.': 'Windows remembers every device ever plugged in and keeps offering its drivers.',
  'absent': 'absent',
  'actif': 'active',
  'active': 'active',
  'admin': 'admin',
  'afficher': 'show',
  'aucun': 'none',
  'aujourd’hui à {time}': 'today at {time}',
  'aussi via {list}': 'also via {list}',
  'automatique': 'automatic',
  'batterie faible': 'low battery',
  'connexion limitée': 'metered connection',
  'copie': 'copy',
  'critique': 'critical',
  'demain à {time}': 'tomorrow at {time}',
  'désactivées': 'disabled',
  'et {n} autre(s)…': 'and {n} more…',
  'expérimental': 'experimental',
  'heures': 'hours',
  'hors plage horaire': 'outside time window',
  'installé': 'installed',
  'installée': 'installed',
  'jamais': 'never',
  'je le ferai moi-même': 'I’ll do it myself',
  'jours': 'days',
  'masquée': 'hidden',
  'masquée(s) dans Windows Update': 'hidden in Windows Update',
  'minutes': 'minutes',
  'mode démo': 'demo mode',
  'nom du processus, ex. firefox': 'process name, e.g. firefox',
  'o': 'B',
  'outil à installer': 'tool to install',
  'par défaut ({n})': 'default ({n})',
  'pilote(s) de périphériques absents': 'driver(s) for absent devices',
  'plein écran / ne pas déranger': 'full screen / do not disturb',
  'portable': 'portable',
  'prochaine {when}': 'next {when}',
  'préversion': 'pre-release',
  'préversion(s)': 'pre-release(s)',
  'quarantaine': 'quarantine',
  'redémarrage': 'restart',
  'reste sur la version {v}.x': 'stays on version {v}.x',
  'sur batterie': 'on battery',
  'sur secteur': 'on AC power',
  'sécurité': 'security',
  'tentative {n}': 'attempt {n}',
  'toujours ignorée': 'always ignored',
  'version {v} ignorée': 'version {v} ignored',
  'version(s) en quarantaine ({d} j)': 'quarantined version(s) ({d} d)',
  'vérifié {when}': 'checked {when}',
  'winget, Scoop, npm, pip, pipx, cargo, outils .NET et extensions VS Code. L’import réinstalle ce qui manque (suivi dans « Activité »).':
    'winget, Scoop, npm, pip, pipx, cargo, .NET tools and VS Code extensions. Import reinstalls what is missing (tracked in “Activity”).',
  '{name} installé': '{name} installed',
  '{n} % de la capacité d’origine': '{n}% of original capacity',
  '{n} en cours': '{n} running',
  '{n} entrée(s)': '{n} entr(y/ies)',
  '{n} firmware/BIOS': '{n} firmware/BIOS',
  '{n} h': '{n} h',
  '{n} heure(s)': '{n} hour(s)',
  '{n} j': '{n} d',
  '{n} jour(s)': '{n} day(s)',
  '{n} min': '{n} min',
  '{n} minutes': '{n} minutes',
  '{n} mise(s) à jour': '{n} update(s)',
  '{n} mise(s) à jour Windows': '{n} Windows update(s)',
  '{n} mise(s) à jour disponible(s)': '{n} update(s) available',
  '{n} mises à jour': '{n} updates',
  '{n} mises à jour lancées': '{n} updates started',
  '{n} paquet(s)': '{n} package(s)',
  '{n} pilote(s)': '{n} driver(s)',
  '{n} sélectionné(s)': '{n} selected',
  '{n} élément(s)': '{n} item(s)',
  'À propos': 'About',
  'Échec': 'Failed',
  'Échec de la mise à jour': 'Update failed',
  'Éditeur': 'Publisher',
  'Évite de devoir saisir la clé de récupération après la mise à jour du firmware.': 'Avoids having to enter the recovery key after the firmware update.',
  'Navigateurs': 'Browsers',
  'Distributions WSL': 'WSL distributions',
  'Outils .NET (global)': '.NET tools (global)',
  'Windows Update (pilotes & firmware)': 'Windows Update (drivers & firmware)',
  'Windows Update (système)': 'Windows Update (system)',
  'Images Docker': 'Docker images',
  'Extensions VS Code': 'VS Code extensions',
  'Lenovo (BIOS, firmware, pilotes)': 'Lenovo (BIOS, firmware, drivers)',
  'Démo': 'Demo',
  'Windows (version)': 'Windows (version)',
  'Intel (graphique)': 'Intel (graphics)',
  'Activable dans les réglages UEFI/BIOS ; protège contre les rootkits de démarrage.': 'Can be enabled in UEFI/BIOS settings; protects against boot rootkits.',
  'Afficher {n} de plus': 'Show {n} more',
  'Analyse du {date}': 'Scan of {date}',
  'Analyse en cours…': 'Scanning…',
  'Anciennes versions de pilotes': 'Old driver versions',
  'Antivirus Microsoft Defender': 'Microsoft Defender Antivirus',
  'Application « {name} » fermée avant la mise à jour.': 'App “{name}” closed before updating.',
  'Aucun problème détecté.': 'No problems detected.',
  'Aucun produit suivi détecté.': 'No tracked product detected.',
  'Aucune mise à jour en attente.': 'No pending updates.',
  'Batterie à {n} % : il faut au moins {min} % pour un firmware/BIOS.': 'Battery at {n}%: at least {min}% is required for firmware/BIOS.',
  'Branchez le chargeur secteur avant une mise à jour de firmware/BIOS.': 'Plug in the charger before a firmware/BIOS update.',
  'CVE corrigées en attente': 'Pending CVE fixes',
  'Cache de Windows Update': 'Windows Update cache',
  'Cache npm': 'npm cache',
  'Cache pip': 'pip cache',
  'Calcul de l’espace récupérable…': 'Calculating reclaimable space…',
  'Ce GPU Intel n’utilise pas le pilote unifié Xe : vérification automatique indisponible.': 'This Intel GPU does not use the unified Xe driver: automatic checking unavailable.',
  'Ce pilote vise un périphérique déjà branché un jour mais absent aujourd’hui.': 'This driver targets a device that was plugged in once but is absent today.',
  'Ces 7 derniers jours': 'Last 7 days',
  'Cette page a rencontré une erreur': 'This page ran into an error',
  'L’interface a rencontré une erreur': 'The interface ran into an error',
  'Chiffrement BitLocker du disque système': 'BitLocker encryption of the system drive',
  'Colonnes et affichage': 'Columns and display',
  'Contrôle': 'Check',
  'Contrôle de compte d’utilisateur (UAC)': 'User Account Control (UAC)',
  'Correct': 'OK',
  'Créer un rapport de diagnostic': 'Create a diagnostic report',
  'Créer…': 'Create…',
  'Dernière version du cycle': 'Latest version of the cycle',
  'Des mises à jour sont disponibles': 'Updates are available',
  'Diagnostic': 'Diagnostics',
  'Délai de {n} min dépassé': 'Timed out after {n} min',
  'Démarrage sécurisé (Secure Boot)': 'Secure Boot',
  'Déroule tout le processus (file, élévation, journal) sans rien installer : idéal pour vérifier ce qui se passerait.':
    'Runs the whole process (queue, elevation, log) without installing anything: ideal to see what would happen.',
  'Détail': 'Detail',
  'Empreinte SHA-256 différente de celle publiée par ASUS.': 'SHA-256 hash differs from the one published by ASUS.',
  'En quarantaine': 'Quarantined',
  'Erreur réseau : nouvelle tentative dans 30 s.': 'Network error: retrying in 30 s.',
  'Espace disque insuffisant : {free} Go libres, environ {need} Go nécessaires.': 'Not enough disk space: {free} GB free, about {need} GB needed.',
  'Espace récupérable : {size}': 'Reclaimable space: {size}',
  'Faille activement exploitée : mise à jour urgente': 'Actively exploited vulnerability: urgent update',
  'Failles activement exploitées': 'Actively exploited vulnerabilities',
  'Fichiers déjà installés conservés par Windows Update (retéléchargés si besoin).': 'Already-installed files kept by Windows Update (downloaded again if needed).',
  'Fichiers texte mis à jour en continu (1 Mo maximum, 3 fichiers conservés).': 'Text files updated continuously (1 MB max, 3 files kept).',
  'Fin de support': 'End of support',
  'Fins de support': 'End of support',
  'Fins de support (endoflife.date), failles exploitées (CISA KEV), vulnérabilités des logiciels de bureau (NVD).':
    'End of support (endoflife.date), exploited vulnerabilities (CISA KEV), desktop software vulnerabilities (NVD).',
  'Gérer les sources': 'Manage sources',
  'Identifiant matériel inconnu pour ce pilote.': 'Unknown hardware ID for this driver.',
  'Ignorer': 'Ignore',
  'Ignorées': 'Ignored',
  'Inconnu': 'Unknown',
  'Installation depuis le site d’Intel (l’installeur Intel n’est pas silencieux).': 'Installed from Intel’s website (Intel’s installer is not silent).',
  'Installation du module LSUClient depuis PowerShell Gallery (portée utilisateur)…': 'Installing the LSUClient module from PowerShell Gallery (user scope)…',
  'Installer LSUClient pour tous les utilisateurs': 'Install LSUClient for all users',
  'Installeur déjà téléchargé : {path}': 'Installer already downloaded: {path}',
  'Installeurs temporaires de winget': 'winget temporary installers',
  'Installeurs temporaires de winget supprimés.': 'winget temporary installers deleted.',
  'Installeurs téléchargés par winget lors des mises à jour.': 'Installers downloaded by winget during updates.',
  'Installées': 'Installed',
  'Intel DSA est installé : il gère aussi les pilotes Wi-Fi et Bluetooth Intel.': 'Intel DSA is installed: it also handles Intel Wi-Fi and Bluetooth drivers.',
  'Interrompu': 'Interrupted',
  'Interruption demandée : le processus administrateur peut terminer l’étape en cours.': 'Stop requested: the administrator process may finish the current step.',
  'Interruption demandée…': 'Stop requested…',
  'Java (OpenJDK)': 'Java (OpenJDK)',
  'Journaux d’UpKeep': 'UpKeep logs',
  'Lecture de Secure Boot, TPM et BitLocker…': 'Reading Secure Boot, TPM and BitLocker…',
  'Lecture de l’état de sécurité…': 'Reading security status…',
  'Les noms et marques cités (Microsoft, Windows, NVIDIA, Intel, AMD, Lenovo, Dell, HP, ASUS…) appartiennent à leurs propriétaires. UpKeep n’est affilié à aucun d’eux.':
    'The names and trademarks mentioned (Microsoft, Windows, NVIDIA, Intel, AMD, Lenovo, Dell, HP, ASUS…) belong to their owners. UpKeep is not affiliated with any of them.',
  'Lien de téléchargement inconnu : relancez une vérification.': 'Unknown download link: run a check again.',
  'Maintenance': 'Maintenance',
  'Masquer les pilotes facultatifs de Windows Update': 'Hide optional Windows Update drivers',
  'Mettez à jour les définitions (onglet Windows des mises à jour).': 'Update the definitions (Windows tab of the updates).',
  'Mise à jour de fonctionnalités': 'Feature update',
  'Mise à jour urgente': 'Urgent update',
  'Mises à jour de sécurité': 'Security updates',
  'Mises à jour de sécurité en attente': 'Pending security updates',
  'Mode simulation': 'Simulation mode',
  'Mode simulation : rien ne sera installé.': 'Simulation mode: nothing will be installed.',
  'Nettoyage': 'Cleanup',
  'Nettoyer': 'Clean up',
  'Nettoyer « {name} » ?': 'Clean up “{name}”?',
  'Nombre de sources interrogées en même temps (moins = moins de charge processeur).': 'Number of sources queried at the same time (fewer = less CPU load).',
  'Notification chaque lundi : installées, échecs, en attente.': 'Notification every Monday: installed, failed, pending.',
  'Nouveautés depuis votre version ({v})': 'What’s new since your version ({v})',
  'Nouvelle version annuelle de Windows (mise à jour de fonctionnalités)': 'New yearly Windows version (feature update)',
  'Nécessite les droits administrateur.': 'Requires administrator rights.',
  'Oubli de périphérique': 'Device removal',
  'Oublier': 'Forget',
  'Oublier ce périphérique': 'Forget this device',
  'Oublier les périphériques absents ?': 'Forget absent devices?',
  'Oublier tous': 'Forget all',
  'Ouvrir le dossier': 'Open folder',
  'Page': 'Page',
  'Page de téléchargement Intel ouverte dans le navigateur.': 'Intel download page opened in the browser.',
  'Paquets Node.js en cache (npm les retélécharge au besoin).': 'Cached Node.js packages (npm downloads them again if needed).',
  'Paquets Python en cache.': 'Cached Python packages.',
  'Paquets remplacés par une version plus récente dans le magasin de pilotes. Windows refuse de supprimer ceux encore utilisés.':
    'Packages superseded by a newer version in the driver store. Windows refuses to delete those still in use.',
  'Pare-feu Windows': 'Windows Firewall',
  'Pas d’installeur Windows pour ce BIOS : mettez-le à jour depuis l’UEFI (EZ Flash).': 'No Windows installer for this BIOS: update it from UEFI (EZ Flash).',
  'Pilote graphique Intel comparé à la dernière version publiée par Intel ; Intel DSA pour le Wi-Fi et le Bluetooth':
    'Intel graphics driver compared with Intel’s latest release; Intel DSA for Wi-Fi and Bluetooth',
  'Pilotes et installeurs téléchargés par UpKeep (NVIDIA, Dell, HP, ASUS, « Télécharger seulement »).': 'Drivers and installers downloaded by UpKeep (NVIDIA, Dell, HP, ASUS, “Download only”).',
  'Pilotes non proposés : une stratégie de l’organisation les exclut de Windows Update (désactivez « Respecter les stratégies » pour passer outre).':
    'Drivers not offered: an organization policy excludes them from Windows Update (turn off “Respect policies” to override).',
  'Plus tard': 'Later',
  'Pour les pilotes Wi-Fi et Bluetooth Intel, installez Intel DSA (action ci-dessous).': 'For Intel Wi-Fi and Bluetooth drivers, install Intel DSA (action below).',
  'Problème': 'Problem',
  'Produit': 'Product',
  'Proposée par Windows Update quand votre PC est éligible ; UpKeep ouvre Windows Update pour la lancer.': 'Offered by Windows Update when your PC is eligible; UpKeep opens Windows Update to start it.',
  'Périphérique absent': 'Absent device',
  'Périphériques absents mémorisés': 'Remembered absent devices',
  'Rapport complet': 'Full report',
  'Rapport créé.': 'Report created.',
  'Rapport de diagnostic': 'Diagnostic report',
  'Rapport de sécurité': 'Security report',
  'Recharger l’interface': 'Reload interface',
  'Recherche globale': 'Global search',
  'Rechercher une page, une mise à jour, un réglage…': 'Search for a page, an update, a setting…',
  'Relance de {path}': 'Relaunching {path}',
  'Respecter les stratégies de l’organisation': 'Respect organization policies',
  'Réessayer': 'Retry',
  'Réglage': 'Setting',
  'Résultats': 'Results',
  'Résumé de la semaine': 'Weekly summary',
  'Résumé hebdomadaire': 'Weekly summary',
  'Sans chiffrement, les données sont lisibles si le PC est volé.': 'Without encryption, data is readable if the PC is stolen.',
  'Si un administrateur exclut les pilotes de Windows Update ou impose un serveur WSUS, UpKeep suit ces règles.':
    'If an administrator excludes drivers from Windows Update or enforces a WSUS server, UpKeep follows these rules.',
  'Signature numérique invalide ou éditeur inattendu : installation bloquée.': 'Invalid digital signature or unexpected publisher: installation blocked.',
  'Source : endoflife.date. Un logiciel en fin de support ne reçoit plus de correctifs de sécurité.': 'Source: endoflife.date. Software past end of support no longer receives security fixes.',
  'Sources d’alertes de sécurité': 'Security alert sources',
  'Suspendre les notifications 4 h': 'Pause notifications for 4 h',
  'Sécurité': 'Security',
  'Sécurité du poste': 'PC security',
  'Tout est à jour': 'Everything is up to date',
  'Téléchargement de {file}…': 'Downloading {file}…',
  'Téléchargements d’UpKeep': 'UpKeep downloads',
  'Téléchargements d’UpKeep supprimés.': 'UpKeep downloads deleted.',
  'Téléchargé : {path}': 'Downloaded: {path}',
  'Version après': 'Version after',
  'Version avant': 'Version before',
  'Version installée : {v}. AMD ne publie pas d’API de versions et son site bloque les accès automatiques : utilisez « Rechercher les mises à jour » dans AMD Software.':
    'Installed version: {v}. AMD publishes no version API and its website blocks automated access: use “Check for updates” in AMD Software.',
  'Voir les mises à jour': 'View updates',
  'Vue compacte': 'Compact view',
  'Vue compacte des listes': 'Compact lists',
  'Vérification en cours…': 'Checking…',
  'Vérifications simultanées': 'Simultaneous checks',
  'Windows Update est ouvert : cliquez sur « Télécharger et installer » si la version est proposée.': 'Windows Update is open: click “Download and install” if the version is offered.',
  'Windows continue de proposer les pilotes des périphériques branchés un jour puis retirés. Les oublier supprime ces propositions.':
    'Windows keeps offering drivers for devices that were plugged in once and then removed. Forgetting them removes these offers.',
  'Windows supprimera ces périphériques de sa mémoire. S’ils sont rebranchés, ils seront simplement redétectés.': 'Windows will remove these devices from memory. If plugged in again, they will simply be detected again.',
  'Windows {family} version {v}': 'Windows {family} version {v}',
  'Zip local (journaux, rapports de plantage, paramètres) à joindre à un signalement. Rien n’est envoyé automatiquement.':
    'Local zip (logs, crash reports, settings) to attach to a report. Nothing is sent automatically.',
  '[simulation] aucune commande n’a été exécutée.': '[simulation] no command was run.',
  '[simulation] {type} via {provider} :': '[simulation] {type} via {provider}:',
  'actif sur tous les profils': 'on for all profiles',
  'actif · définitions de {n} jour(s)': 'on · definitions {n} day(s) old',
  'activé': 'enabled',
  'bientôt': 'soon',
  'chiffrement en cours': 'encrypting',
  'désactivé': 'disabled',
  'désactivé pour : {list}': 'off for: {list}',
  'erreur': 'error',
  'exploitée': 'exploited',
  'facultatif': 'optional',
  'inconnu': 'unknown',
  'inconnu (BIOS hérité ?)': 'unknown (legacy BIOS?)',
  'inconnue': 'unknown',
  'les oublier': 'forget them',
  'maintenu': 'supported',
  'manuelle': 'manual',
  'non annoncée': 'not announced',
  'non disponible': 'unavailable',
  'non disponible (autre antivirus ?)': 'unavailable (another antivirus?)',
  'présent · version {v}': 'present · version {v}',
  'simulation': 'simulation',
  'suspendu': 'suspended',
  'terminé': 'ended',
  'vide': 'empty',
  '{n} ligne(s) précédente(s)': '{n} earlier line(s)',
  '{n} mise(s) à jour corrigent une faille activement exploitée.': '{n} update(s) fix an actively exploited vulnerability.',
  '{n} mise(s) à jour de sécurité à installer.': '{n} security update(s) to install.',
  '{n} mise(s) à jour installée(s), {f} échec(s), {p} en attente, {q} en quarantaine.': '{n} update(s) installed, {f} failed, {p} pending, {q} quarantined.',
  '{n} mise(s) à jour, aucune urgente.': '{n} update(s), none urgent.',
  '{n} pilote(s) proposés': '{n} driver(s) offered',
  '{n} source(s) actives sur {total}.': '{n} of {total} source(s) active.',
  '{p} : fin de support le {d}': '{p}: end of support on {d}',
  '{p} n’est plus maintenu': '{p} is no longer supported',
  '{s} s': '{s} s',
  '« {name} » ignorée': '“{name}” ignored',
  'À surveiller': 'Watch',
  'Échec, nouvelle tentative dans 5 s': 'Failed, retrying in 5 s',
  'Échecs': 'Failures',
  'Élément': 'Item',
  'État': 'Status',
  'État avant la mise à jour': 'Status before the update',
  'État du poste': 'PC status',
  "Pour : {name}": "For: {name}",
  "Périphérique absent : {name}": "Absent device: {name}",
  "démo": "demo",
  "Licence : PolyForm Noncommercial 1.0.0. Toute utilisation commerciale nécessite une licence commerciale.": "License: PolyForm Noncommercial 1.0.0. Any commercial use requires a commercial license.",
  "UpKeep {v} est prêt": "UpKeep {v} is ready",
  "La mise à jour sera installée à la fermeture d’UpKeep, ou tout de suite depuis « À propos ».": "The update will be installed when UpKeep closes, or right away from “About”.",
  "UpKeep {v} est disponible": "UpKeep {v} is available",
  "Détails dans « À propos ».": "Details in “About”.",
  "Dernière vérification : {date}": "Last check: {date}",
  "Recherche d’une nouvelle version…": "Looking for a new version…",
  "UpKeep est à jour.": "UpKeep is up to date.",
  "La version {v} est disponible.": "Version {v} is available.",
  "Téléchargement de la version {v}… {p} %": "Downloading version {v}… {p}%",
  "La version {v} est téléchargée : elle sera installée à la fermeture d’UpKeep.": "Version {v} is downloaded: it will be installed when UpKeep closes.",
  "Échec de la recherche de mise à jour : {error}": "Update check failed: {error}",
  "Redémarrer et installer": "Restart and install",
  "Télécharger et installer": "Download and install",
  "Ouvrir la page de téléchargement": "Open the download page",
  "Rechercher une mise à jour d’UpKeep": "Check for UpKeep updates",
  "Mettre à jour UpKeep automatiquement": "Update UpKeep automatically",
  "Recherche les nouvelles versions publiées sur GitHub. La version installée les télécharge et les installe à sa fermeture ; les versions portable, MSI et ZIP signalent seulement la nouvelle version.": "Looks for new versions published on GitHub. The installed version downloads them and installs them when it closes; the portable, MSI and ZIP versions only report the new version.",
  "Rechercher des logiciels": "Find software",
  "Trouvez un logiciel dans les catalogues de vos gestionnaires de paquets et installez-le.": "Find software in your package managers’ catalogs and install it.",
  "Nom ou identifiant (ex. vlc, 7zip)": "Name or ID (e.g. vlc, 7zip)",
  "Logiciel à rechercher": "Software to search for",
  "Masquer les logiciels déjà installés": "Hide software already installed",
  "Catalogues": "Catalogs",
  "{name} n’est pas installé sur ce PC.": "{name} is not installed on this PC.",
  "Aucun gestionnaire de paquets n’est installé sur ce PC (WinGet, Scoop ou Chocolatey).": "No package manager is installed on this PC (WinGet, Scoop or Chocolatey).",
  "{name} : {error}": "{name}: {error}",
  "Recherche dans les catalogues…": "Searching the catalogs…",
  "Tapez le nom d’un logiciel puis Entrée.": "Type the name of a program, then press Enter.",
  "Aucun résultat pour « {q} ».": "No results for “{q}”.",
  "Résultats de la recherche": "Search results",
  "en file": "queued",
  "Chocolatey demande les droits administrateur.": "Chocolatey requires administrator rights.",
  "Installer (admin)": "Install (admin)",
  "Installer": "Install",
  "Installation de {name} ajoutée à la file.": "Installation of {name} added to the queue.",
  "Source indisponible : {name}": "Source unavailable: {name}",
  "Recherche refusée : 2 à 100 caractères, lettres, chiffres et . + # _ @ / -": "Search refused: 2 to 100 characters, letters, digits and . + # _ @ / -",
};
