export const ES: Record<string, string> = {
  " — redémarrage requis": " — reinicio necesario",
  "(aucune sortie pour le moment)": "(aún sin salida)",
  "(indisponible)": "(no disponible)",
  "(vide)": "(vacío)",
  "1 jour": "1 día",
  "1 semaine": "1 semana",
  "30 derniers jours": "Últimos 30 días",
  "7 derniers jours": "Últimos 7 días",
  "90 derniers jours": "Últimos 90 días",
  "Accueil": "Inicio",
  "Action": "Acción",
  "Activable dans les réglages UEFI/BIOS ; protège contre les rootkits de démarrage.": "Se puede activar en la configuración UEFI/BIOS; protege contra rootkits de arranque.",
  "Activer": "Activar",
  "Activer l’assistant administrateur ?": "¿Activar el asistente de administrador?",
  "Activité": "Actividad",
  "Activé": "Activado",
  "Actualiser": "Actualizar",
  "Afficher les mises à jour masquées dans Windows Update": "Mostrar las actualizaciones ocultas en Windows Update",
  "Afficher quand même les versions en quarantaine": "Mostrar igualmente las versiones en cuarentena",
  "Afficher {n} de plus": "Mostrar {n} más",
  "Ajouter une règle": "Añadir una regla",
  "Analyse du {date}": "Análisis del {date}",
  "Analyse en cours…": "Analizando…",
  "Anciennes versions de pilotes": "Versiones antiguas de controladores",
  "Annuler": "Cancelar",
  "Annuler le redémarrage": "Cancelar el reinicio",
  "Annulé": "Cancelado",
  "Antivirus Microsoft Defender": "Antivirus Microsoft Defender",
  "Apparence": "Apariencia",
  "Application « {name} » fermée avant la mise à jour.": "Aplicación «{name}» cerrada antes de actualizar.",
  "Application à fermer": "Aplicación que cerrar",
  "Applications": "Aplicaciones",
  "Applications Python isolées installées avec pipx": "Aplicaciones Python aisladas instaladas con pipx",
  "Applications du Microsoft Store (via winget, source msstore)": "Aplicaciones de Microsoft Store (vía winget, origen msstore)",
  "Applique ses réglages par-dessus les paramètres. Aussi accessible depuis la zone de notification.": "Aplica sus ajustes por encima de la configuración. También disponible desde el área de notificación.",
  "Architecture": "Arquitectura",
  "Arguments supplémentaires pour l’installeur": "Argumentos adicionales del instalador",
  "Assistant administrateur": "Asistente de administrador",
  "Associer": "Vincular",
  "Associer « {name} » à un paquet winget": "Vincular «{name}» a un paquete winget",
  "Au démarrage, une source vérifiée plus récemment que ce délai n’est pas réinterrogée.": "Al iniciar, no se vuelven a consultar las fuentes comprobadas hace menos de este tiempo.",
  "Aucun": "Ninguna",
  "Aucun outil connu": "Ninguna herramienta conocida",
  "Aucun paquet trouvé.": "No se encontró ningún paquete.",
  "Aucun pilote Studio publié pour ce GPU : UpKeep propose la branche Game Ready.": "No se publica ningún controlador Studio para esta GPU: UpKeep ofrece la rama Game Ready.",
  "Aucun problème détecté.": "No se detectó ningún problema.",
  "Aucun produit suivi détecté.": "No se detectó ningún producto supervisado.",
  "Aucun périphérique Logitech, Razer, SteelSeries ou Corsair connecté.": "No hay ningún dispositivo Logitech, Razer, SteelSeries o Corsair conectado.",
  "Aucun résultat.": "Sin resultados.",
  "Aucune activité.": "Sin actividad.",
  "Aucune mise à jour en attente.": "No hay actualizaciones pendientes.",
  "Aucune règle.": "Sin reglas.",
  "Aucune.": "Ninguno.",
  "UpKeep surveille les mises à jour de vos logiciels, de Windows, de vos pilotes et de votre BIOS, et les installe quand vous le décidez.": "UpKeep vigila las actualizaciones de tus programas, Windows, controladores y BIOS, y las instala cuando tú decides.",
  "UpKeep tourne avec les droits administrateur.": "UpKeep se está ejecutando con derechos de administrador.",
  "UpKeep — vérification en cours…": "UpKeep — comprobando…",
  "UpKeep — {n} mise(s) à jour disponible(s)": "UpKeep — {n} actualización(es) disponible(s)",
  "Automatiques en pause : {why}": "Actualizaciones automáticas en pausa: {why}",
  "Automatisation": "Automatización",
  "BIOS installé :": "BIOS instalada:",
  "BIOS publié sur le site de support ASUS pour votre modèle": "BIOS publicada en el sitio de soporte de ASUS para tu modelo",
  "BIOS, firmware et pilotes Dell via dcu-cli": "BIOS, firmware y controladores Dell vía dcu-cli",
  "BIOS, firmware et pilotes HP analysés par HP Image Assistant": "BIOS, firmware y controladores HP analizados por HP Image Assistant",
  "Batterie": "Batería",
  "Batterie : {n} %": "Batería: {n} %",
  "Batterie minimale pour un firmware/BIOS": "Batería mínima para firmware/BIOS",
  "Batterie à {n} % : il faut au moins {min} % pour un firmware/BIOS.": "Batería al {n} %: se necesita al menos un {min} % para firmware/BIOS.",
  "Bienvenue dans UpKeep": "Bienvenido a UpKeep",
  "Binaires Rust installés avec « cargo install »": "Binarios de Rust instalados con «cargo install»",
  "BitLocker sera suspendu pour un redémarrage.": "BitLocker se suspenderá durante un reinicio.",
  "Bloquer en connexion limitée": "Bloquear en conexión de uso medido",
  "Branche des pilotes NVIDIA": "Rama de controladores NVIDIA",
  "Branchez le chargeur secteur avant une mise à jour de firmware/BIOS.": "Conecta el cargador antes de una actualización de firmware/BIOS.",
  "CVE corrigées en attente": "Correcciones de CVE pendientes",
  "Cache de Windows Update": "Caché de Windows Update",
  "Cache des résultats": "Caché de resultados",
  "Cache npm": "Caché de npm",
  "Cache pip": "Caché de pip",
  "Calcul de l’espace récupérable…": "Calculando el espacio recuperable…",
  "Carte mère": "Placa base",
  "Cartes graphiques": "Tarjetas gráficas",
  "Catalogue constructeur Lenovo via le module PowerShell LSUClient": "Catálogo de Lenovo vía el módulo PowerShell LSUClient",
  "Ce GPU Intel n’utilise pas le pilote unifié Xe : vérification automatique indisponible.": "Esta GPU Intel no usa el controlador unificado Xe: comprobación automática no disponible.",
  "Ce PC est configuré pour un serveur WSUS ({srv}) ; UpKeep interroge tout de même Windows Update directement.": "Este PC está configurado para un servidor WSUS ({srv}); UpKeep consulta igualmente Windows Update directamente.",
  "Ce PC est géré par une organisation (Intune / MDM) : certaines mises à jour peuvent être bloquées par stratégie.": "Este PC está administrado por una organización (Intune / MDM): algunas actualizaciones pueden estar bloqueadas por directivas.",
  "Ce pilote vise un périphérique déjà branché un jour mais absent aujourd’hui.": "Este controlador corresponde a un dispositivo que se conectó una vez pero hoy no está presente.",
  "Ces 7 derniers jours": "Últimos 7 días",
  "Ces applications seront fermées avant la mise à jour : {list}": "Estas aplicaciones se cerrarán antes de actualizar: {list}",
  "Ces programmes ne sont suivis par aucun gestionnaire. Associez-les à un paquet winget pour qu’UpKeep surveille leurs mises à jour.": "Estos programas no están seguidos por ningún gestor de paquetes. Vincúlalos a un paquete winget para que UpKeep vigile sus actualizaciones.",
  "Cette page a rencontré une erreur": "Esta página ha encontrado un error",
  "L’interface a rencontré une erreur": "La interfaz ha encontrado un error",
  "Champ": "Campo",
  "Charge": "Carga",
  "Chargement des détails…": "Cargando detalles…",
  "Chargement…": "Cargando…",
  "Charger les versions": "Cargar versiones",
  "Chiffrement BitLocker du disque système": "Cifrado BitLocker de la unidad del sistema",
  "Choisir": "Elegir",
  "Choisir…": "Elegir…",
  "Chrome, Edge et Firefox comparés à la dernière version stable publiée": "Chrome, Edge y Firefox comparados con la última versión estable",
  "Clair": "Claro",
  "Colonnes et affichage": "Columnas y visualización",
  "Comme les paramètres": "Igual que la configuración",
  "Commencer": "Empezar",
  "Composants, firmwares et outils constructeur.": "Componentes, firmware y herramientas del fabricante.",
  "Confirmer": "Confirmar",
  "Confirmer le téléchargement": "Confirmar la descarga",
  "Confirmer l’installation": "Confirmar la instalación",
  "Connexion limitée": "Conexión de uso medido",
  "Contrôle": "Control",
  "Contrôle de compte d’utilisateur (UAC)": "Control de cuentas de usuario (UAC)",
  "Copier": "Copiar",
  "Copier le journal": "Copiar el registro",
  "Copier l’identifiant": "Copiar el ID",
  "Copié !": "¡Copiado!",
  "Correct": "Aceptar",
  "Crée une tâche planifiée Windows (sans droits administrateur) qui lance une vérification à la fréquence choisie.": "Crea una tarea programada de Windows (sin derechos de administrador) que ejecuta una comprobación con la frecuencia elegida.",
  "Créer un rapport de diagnostic": "Crear un informe de diagnóstico",
  "Créer…": "Crear…",
  "Date": "Fecha",
  "Dernier pilote Game Ready ou Studio publié par NVIDIA pour votre carte graphique": "Último controlador Game Ready o Studio publicado por NVIDIA para tu tarjeta gráfica",
  "Dernière version du cycle": "Última versión del ciclo",
  "Dernière vérification : {last} · prochaine {next}": "Última comprobación: {last} · próxima {next}",
  "Des mises à jour attendent un redémarrage pour être finalisées.": "Algunas actualizaciones esperan un reinicio para completarse.",
  "Des mises à jour sont disponibles": "Hay actualizaciones disponibles",
  "Descendre": "Bajar",
  "Description": "Descripción",
  "Diagnostic": "Diagnóstico",
  "Dim": "Dom",
  "Disponible": "Disponible",
  "Disques et firmware": "Discos y firmware",
  "Dissocier ({id})": "Desvincular ({id})",
  "Docker n’est pas démarré : les images ne peuvent pas être vérifiées.": "Docker no se está ejecutando: no se pueden comprobar las imágenes.",
  "Dossier des téléchargements": "Carpeta de descargas",
  "Dupliquer": "Duplicar",
  "Durée": "Duración",
  "Début": "Inicio",
  "Délai de {n} min dépassé": "Tiempo agotado tras {n} min",
  "Délai max (min)": "Tiempo límite (min)",
  "Démarrage sécurisé (Secure Boot)": "Arranque seguro (Secure Boot)",
  "Démarre réduit dans la zone de notification (version installée uniquement).": "Se inicia minimizado en el área de notificación (solo versión instalada).",
  "Démarrer masqué": "Iniciar oculto",
  "Déroule tout le processus (file, élévation, journal) sans rien installer : idéal pour vérifier ce qui se passerait.": "Ejecuta todo el proceso (cola, elevación, registro) sin instalar nada: ideal para ver qué ocurriría.",
  "Désactiver": "Desactivar",
  "Désactivé": "Desactivado",
  "Désactivée": "Desactivada",
  "Désépingler": "Desfijar",
  "Détail": "Detalle",
  "Détails": "Detalles",
  "Développement": "Desarrollo",
  "Empreinte SHA-256 différente de celle publiée par ASUS.": "El hash SHA-256 difiere del publicado por ASUS.",
  "En attente": "En cola",
  "En cours": "En curso",
  "En cours…": "En curso…",
  "En pause actuellement : {why}": "Actualmente en pausa: {why}",
  "En quarantaine": "En cuarentena",
  "En quarantaine jusqu’au {date} (version récente).": "En cuarentena hasta el {date} (versión reciente).",
  "Enregistrez votre travail : Windows redémarre immédiatement.": "Guarda tu trabajo: Windows se reinicia inmediatamente.",
  "Entrée": "Intro",
  "Erreur": "Error",
  "Erreur réseau : nouvelle tentative dans 30 s.": "Error de red: nuevo intento en 30 s.",
  "Espace disque insuffisant : {free} Go libres, environ {need} Go nécessaires.": "Espacio en disco insuficiente: {free} GB libres, se necesitan unos {need} GB.",
  "Espace récupérable : {size}": "Espacio recuperable: {size}",
  "Exiger le secteur pour un firmware/BIOS": "Exigir alimentación de red para firmware/BIOS",
  "Export / import": "Exportar / importar",
  "Export annulé.": "Exportación cancelada.",
  "Export lancé (voir Activité).": "Exportación iniciada (ver Actividad).",
  "Exporter": "Exportar",
  "Exporter en CSV": "Exportar a CSV",
  "Exporté vers {path}": "Exportado a {path}",
  "Extensions Visual Studio Code dont une version plus récente existe sur le Marketplace": "Extensiones de Visual Studio Code con una versión más reciente en el Marketplace",
  "Faille activement exploitée : mise à jour urgente": "Vulnerabilidad explotada activamente: actualización urgente",
  "Failles activement exploitées": "Vulnerabilidades explotadas activamente",
  "Fermer": "Cerrar",
  "Fichier de paramètres UpKeep invalide.": "Archivo de configuración de UpKeep no válido.",
  "Fichiers déjà installés conservés par Windows Update (retéléchargés si besoin).": "Archivos ya instalados conservados por Windows Update (se vuelven a descargar si es necesario).",
  "Fichiers texte mis à jour en continu (1 Mo maximum, 3 fichiers conservés).": "Archivos de texto actualizados continuamente (1 MB máx., se conservan 3 archivos).",
  "Filtres": "Filtros",
  "Fin": "Fin",
  "Fin de support": "Fin de soporte",
  "Fins de support": "Fin del soporte",
  "Fins de support (endoflife.date), failles exploitées (CISA KEV), vulnérabilités des logiciels de bureau (NVD).": "Fin de soporte (endoflife.date), vulnerabilidades explotadas (CISA KEV), vulnerabilidades de software de escritorio (NVD).",
  "Firmware": "Firmware",
  "Firmware & BIOS": "Firmware y BIOS",
  "Forfait mobile, partage de connexion…": "Datos móviles, conexión compartida…",
  "Fréquence": "Frecuencia",
  "Fréquence de vérification": "Frecuencia de comprobación",
  "Fréquence globale": "Frecuencia global",
  "Gestionnaire de paquets Chocolatey (nécessite les droits administrateur)": "Gestor de paquetes Chocolatey (requiere derechos de administrador)",
  "Gestionnaire de paquets Windows (Microsoft)": "Administrador de paquetes de Windows (Microsoft)",
  "Gestionnaires de paquets, Windows Update, pilotes graphiques et outils constructeur.": "Gestores de paquetes, Windows Update, controladores gráficos y herramientas del fabricante.",
  "Go": "GB",
  "Graphique": "Gráfico",
  "Graphique en barres empilées": "Gráfico de barras apiladas",
  "Grouper": "Agrupar",
  "Général": "General",
  "Gérer les sources": "Gestionar las fuentes",
  "Heure": "Hora",
  "Identifiant": "ID",
  "Identifiant matériel inconnu pour ce pilote.": "ID de hardware desconocido para este controlador.",
  "Ignorer": "Ignorar",
  "Ignorer cette version": "Ignorar esta versión",
  "Ignorées": "Ignoradas",
  "Ignorées & épinglées": "Ignoradas y fijadas",
  "Images locales dont une version plus récente est publiée sur Docker Hub": "Imágenes locales con una compilación más reciente publicada en Docker Hub",
  "Import lancé (voir Activité).": "Importación iniciada (ver Actividad).",
  "Importer": "Importar",
  "Inconnu": "Desconocido",
  "Infos": "Información",
  "Installateur en ligne de commande pour Windows": "Instalador de línea de comandos para Windows",
  "Installation": "Instalación",
  "Installation depuis le site d’Intel (l’installeur Intel n’est pas silencieux).": "Instalado desde el sitio de Intel (el instalador de Intel no es silencioso).",
  "Installation du module LSUClient depuis PowerShell Gallery (portée utilisateur)…": "Instalando el módulo LSUClient desde PowerShell Gallery (ámbito de usuario)…",
  "Installation impossible": "No se puede instalar",
  "Installation via l’assistant administrateur (sans fenêtre UAC).": "Instalado mediante el asistente de administrador (sin solicitud UAC).",
  "Installations en cours, file d’attente et historique.": "Instalaciones en curso, cola e historial.",
  "Installations en parallèle": "Instalaciones en paralelo",
  "Installe sans intervention les mises à jour des sources et paquets marqués « automatique » (Sources › Réglages, ou panneau de détail).": "Instala sin intervención las actualizaciones de las fuentes y paquetes marcados como «automático» (Fuentes › Ajustes, o el panel de detalles).",
  "Installer (une fenêtre UAC)": "Instalar (una sola solicitud UAC)",
  "Installer Dell Command | Update (winget)": "Instalar Dell Command | Update (winget)",
  "Installer HP Image Assistant (winget)": "Instalar HP Image Assistant (winget)",
  "Installer Intel DSA (winget)": "Instalar Intel DSA (winget)",
  "Installer LSUClient pour tous les utilisateurs": "Instalar LSUClient para todos los usuarios",
  "Installer ces mises à jour ? (o/N) ": "¿Instalar estas actualizaciones? (s/N)",
  "Installer cette version": "Instalar esta versión",
  "Installer le module LSUClient": "Instalar el módulo LSUClient",
  "Installer le module Microsoft.WinGet.Client": "Instalar el módulo Microsoft.WinGet.Client",
  "Installer sans fenêtre UAC": "Instalar sin solicitudes UAC",
  "Installer une version précise": "Instalar una versión concreta",
  "Installer {n} élément(s)": "Instalar {n} elemento(s)",
  "Installeur déjà téléchargé : {path}": "Instalador ya descargado: {path}",
  "Installeurs temporaires de winget": "Instaladores temporales de winget",
  "Installeurs temporaires de winget supprimés.": "Instaladores temporales de winget eliminados.",
  "Installeurs téléchargés par winget lors des mises à jour.": "Instaladores descargados por winget durante las actualizaciones.",
  "Installé le": "Instalado el",
  "Installée": "Instalado",
  "Installées": "Instalada",
  "Intel DSA est installé : il gère aussi les pilotes Wi-Fi et Bluetooth Intel.": "Intel DSA está instalado: también gestiona los controladores Wi-Fi y Bluetooth de Intel.",
  "Interrompre": "Interrumpir",
  "Interrompu": "Interrumpido",
  "Interruption demandée : le processus administrateur peut terminer l’étape en cours.": "Interrupción solicitada: el proceso de administrador puede terminar el paso en curso.",
  "Interruption demandée…": "Interrupción solicitada…",
  "Inventaire": "Inventario",
  "Jamais": "Nunca",
  "Jamais automatique": "Nunca automático",
  "Jamais automatiquement": "Nunca automáticamente",
  "Jamais bloquer": "Nunca bloquear",
  "Java (OpenJDK)": "Java (OpenJDK)",
  "Jeu": "Jue",
  "Jokers : * = n’importe quelle suite, ? = un caractère. Exemples : *.Preview, Microsoft.*, *chrome*.": "Comodines: * = cualquier secuencia, ? = un carácter. Ejemplos: *.Preview, Microsoft.*, *chrome*.",
  "Journal": "Registro",
  "Journal de diagnostic — {name}": "Registro de diagnóstico — {name}",
  "Journal des modifications": "Registro de cambios",
  "Journaux d’UpKeep": "Registros de UpKeep",
  "Jours": "Días",
  "Ko": "KB",
  "Lancer avec Windows": "Iniciar con Windows",
  "Lancer avec Windows (réduit dans la zone de notification)": "Iniciar con Windows (minimizado en el área de notificación)",
  "Langue": "Idioma",
  "Langue de Windows": "Idioma de Windows",
  "Le firmware de ces périphériques se met à jour depuis le logiciel du fabricant.": "El firmware de estos dispositivos se actualiza desde el software del fabricante.",
  "Le pilote installé pour « {name} » sera retiré du magasin de pilotes ; Windows reviendra à la version précédente. Un redémarrage peut être nécessaire.": "El controlador instalado para «{name}» se eliminará del almacén de controladores; Windows volverá a la versión anterior. Puede ser necesario reiniciar.",
  "Lecture de Secure Boot, TPM et BitLocker…": "Leyendo Secure Boot, TPM y BitLocker…",
  "Lecture de l’état de sécurité…": "Leyendo el estado de seguridad…",
  "Lecture des programmes installés…": "Leyendo los programas instalados…",
  "Lecture du matériel…": "Leyendo el hardware…",
  "Les firmwares/BIOS ne sont pas inclus : installez-les depuis la fenêtre principale.": "Los firmwares/BIOS no están incluidos: instálalos desde la ventana principal.",
  "Les installations automatiques n’ont lieu que pendant cette plage.": "Las instalaciones automáticas solo se realizan durante esta franja.",
  "Les installations qui le nécessitent demanderont une élévation (UAC).": "Las instalaciones que lo necesiten pedirán elevación (UAC).",
  "Les noms et marques cités (Microsoft, Windows, NVIDIA, Intel, AMD, Lenovo, Dell, HP, ASUS…) appartiennent à leurs propriétaires. UpKeep n’est affilié à aucun d’eux.": "Los nombres y marcas citados (Microsoft, Windows, NVIDIA, Intel, AMD, Lenovo, Dell, HP, ASUS…) pertenecen a sus propietarios. UpKeep no está afiliado a ninguno de ellos.",
  "Les paramètres de base ne sont pas modifiés.": "La configuración base no se modifica.",
  "Licence": "Licencia",
  "Lien de téléchargement inconnu : relancez une vérification.": "Enlace de descarga desconocido: vuelve a comprobar.",
  "Ligne de commande : upkeep-cli --check [--json] · --list · --install-all · --profile=<id>": "Línea de comandos: upkeep-cli --check [--json] · --list · --install-all · --profile=<id>",
  "Liste des logiciels et paquets": "Lista de programas y paquetes",
  "Liste des paquets": "Lista de paquetes",
  "Logiciels installés": "Programas instalados",
  "Lun": "Lun",
  "Machine": "Equipo",
  "Maintenance": "Mantenimiento",
  "Mar": "Mar",
  "Masquer les pilotes de périphériques absents": "Ocultar los controladores de dispositivos ausentes",
  "Masquer les pilotes facultatifs de Windows Update": "Ocultar los controladores opcionales de Windows Update",
  "Masquer les préversions (bêta, RC…)": "Ocultar las versiones preliminares (beta, RC…)",
  "Masquées :": "Ocultas:",
  "Matériel": "Hardware",
  "Mer": "Mié",
  "Mettez à jour les définitions (onglet Windows des mises à jour).": "Actualiza las definiciones (pestaña Windows de las actualizaciones).",
  "Mettre à jour": "Actualizar",
  "Mettre à jour automatiquement": "Actualizar automáticamente",
  "Mettre à jour la sélection": "Actualizar la selección",
  "Microsoft Store": "Microsoft Store",
  "Mise à jour automatique": "Actualización automática",
  "Mise à jour de firmware/BIOS : branchez le chargeur secteur, fermez vos applications et n’interrompez pas le redémarrage.": "Actualización de firmware/BIOS: conecta el cargador, cierra tus aplicaciones y no interrumpas el reinicio.",
  "Mise à jour de fonctionnalités": "Actualización de características",
  "Mise à jour de sécurité": "Actualización de seguridad",
  "Mise à jour de « {name} » lancée": "Actualización de «{name}» iniciada",
  "Mise à jour terminée": "Actualización terminada",
  "Mise à jour urgente": "Actualización urgente",
  "Mises à jour": "Actualizaciones",
  "Mises à jour automatiques": "Actualizaciones automáticas",
  "Mises à jour cumulatives, Defender, .NET, Office et autres produits Microsoft": "Actualizaciones acumulativas, Defender, .NET, Office y otros productos de Microsoft",
  "Mises à jour de sécurité": "Actualizaciones de seguridad",
  "Mises à jour de sécurité disponibles": "Actualizaciones de seguridad disponibles",
  "Mises à jour de sécurité en attente": "Actualizaciones de seguridad pendientes",
  "Mises à jour disponibles": "Actualizaciones disponibles",
  "Mises à jour ignorées": "Actualizaciones ignoradas",
  "Mises à jour installées par mois": "Actualizaciones instaladas por mes",
  "Mo": "MB",
  "Mode simulation": "Modo simulación",
  "Mode simulation : rien ne sera installé.": "Modo simulación: no se instalará nada.",
  "Modifier": "Editar",
  "Modifier un profil": "Editar un perfil",
  "Modifier…": "Cambiar…",
  "Modules PowerShell installés avec Install-Module": "Módulos de PowerShell instalados con Install-Module",
  "Modèle": "Modelo",
  "Mois": "Mes",
  "Monter": "Subir",
  "Motif": "Patrón",
  "Mémoire": "Memoria",
  "Navigation": "Navegación",
  "Ne pas déranger": "No molestar",
  "Ne pas déranger en plein écran": "No molestar en pantalla completa",
  "Ne pas déranger en plein écran, en jeu ou en mode Focus": "No molestar en pantalla completa, en juegos o en modo Concentración",
  "Ne pas notifier": "No notificar",
  "Ne pas redémarrer": "No reiniciar",
  "Ne plus ignorer": "Dejar de ignorar",
  "Nettoyage": "Limpieza",
  "Nettoyer": "Limpiar",
  "Nettoyer « {name} » ?": "¿Limpiar «{name}»?",
  "Nom": "Nombre",
  "Nombre de sources interrogées en même temps (moins = moins de charge processeur).": "Número de fuentes consultadas a la vez (menos = menos carga de procesador).",
  "Non applicable à ce PC": "No aplicable a este PC",
  "Non suivis": "No seguidos",
  "Notes de version": "Notas de la versión",
  "Notification chaque lundi : installées, échecs, en attente.": "Notificación cada lunes: instaladas, errores, pendientes.",
  "Notifications": "Notificaciones",
  "Notifications Windows": "Notificaciones de Windows",
  "Nouveau": "Nuevo",
  "Nouveau profil": "Nuevo perfil",
  "Nouveautés depuis votre version ({v})": "Novedades desde tu versión ({v})",
  "Nouvelle version annuelle de Windows (mise à jour de fonctionnalités)": "Nueva versión anual de Windows (actualización de características)",
  "Nouvelles mises à jour disponibles": "Nuevas actualizaciones disponibles",
  "Nouvelles mises à jour, fin des installations, rappels de redémarrage.": "Nuevas actualizaciones, instalaciones terminadas, recordatorios de reinicio.",
  "Nécessaire pour la vérification périodique en arrière-plan.": "Necesario para la comprobación periódica en segundo plano.",
  "Nécessite les droits administrateur.": "Requiere derechos de administrador.",
  "Options winget": "Opciones de winget",
  "Oubli de périphérique": "Olvido de dispositivo",
  "Oublier": "Olvidar",
  "Oublier ce périphérique": "Olvidar este dispositivo",
  "Oublier les périphériques absents ?": "¿Olvidar los dispositivos ausentes?",
  "Oublier tous": "Olvidar todos",
  "Outil": "Herramienta",
  "Outil de mise à jour": "Herramienta de actualización",
  "Outil non installé": "Herramienta no instalada",
  "Outils installés avec « dotnet tool install -g »": "Herramientas instaladas con «dotnet tool install -g»",
  "Ouvrir": "Abrir",
  "Ouvrir UpKeep": "Abrir UpKeep",
  "Ouvrir Intel DSA": "Abrir Intel DSA",
  "Ouvrir la page des pilotes AMD": "Abrir la página de controladores de AMD",
  "Ouvrir le dossier": "Abrir la carpeta",
  "Ouvrir le dossier des téléchargements": "Abrir la carpeta de descargas",
  "Ouvrir le site": "Abrir el sitio",
  "Page": "Página",
  "Page de téléchargement Intel ouverte dans le navigateur.": "Página de descarga de Intel abierta en el navegador.",
  "Paquets": "Paquetes",
  "Paquets Node.js en cache (npm les retélécharge au besoin).": "Paquetes de Node.js en caché (npm los vuelve a descargar si es necesario).",
  "Paquets Node.js installés avec « yarn global add »": "Paquetes de Node.js instalados con «yarn global add»",
  "Paquets Node.js installés globalement avec npm": "Paquetes de Node.js instalados globalmente con npm",
  "Paquets Node.js installés globalement avec pnpm": "Paquetes de Node.js instalados globalmente con pnpm",
  "Paquets Python de l’interpréteur par défaut": "Paquetes de Python del intérprete predeterminado",
  "Paquets Python en cache.": "Paquetes de Python en caché.",
  "Paquets apt / dnf / pacman / zypper des distributions WSL (démarre les distributions pour vérifier)": "Paquetes apt / dnf / pacman / zypper de las distribuciones WSL (inicia las distribuciones para comprobar)",
  "Paquets installés avec « bun add -g »": "Paquetes instalados con «bun add -g»",
  "Paquets remplacés par une version plus récente dans le magasin de pilotes. Windows refuse de supprimer ceux encore utilisés.": "Paquetes reemplazados por una versión más reciente en el almacén de controladores. Windows se niega a eliminar los que aún están en uso.",
  "Par défaut": "Predeterminado",
  "Par source": "Por fuente",
  "Par type": "Por tipo",
  "Paramètres": "Configuración",
  "Paramètres d’UpKeep": "Configuración de UpKeep",
  "Paramètres exportés.": "Configuración exportada.",
  "Paramètres importés.": "Configuración importada.",
  "Pare-feu Windows": "Firewall de Windows",
  "Partiel": "Parcial",
  "Pas d’installation automatique en connexion limitée": "Sin instalación automática en conexión de uso medido",
  "Pas d’installation automatique sur batterie sous": "Sin instalación automática con batería por debajo de",
  "Pas d’installeur Windows pour ce BIOS : mettez-le à jour depuis l’UEFI (EZ Flash).": "No hay instalador de Windows para esta BIOS: actualízala desde la UEFI (EZ Flash).",
  "Passer": "Omitir",
  "Pastille du nombre de mises à jour sur l’icône de la barre des tâches": "Indicador del número de actualizaciones en el icono de la barra de tareas",
  "Pilote graphique Intel comparé à la dernière version publiée par Intel ; Intel DSA pour le Wi-Fi et le Bluetooth": "Controlador gráfico Intel comparado con la última versión publicada por Intel; Intel DSA para Wi-Fi y Bluetooth",
  "Pilotes": "Controladores",
  "Pilotes & firmware": "Controladores y firmware",
  "Pilotes et firmwares (UEFI/BIOS, contrôleurs…) distribués par Windows Update": "Controladores y firmware (UEFI/BIOS, controladoras…) distribuidos por Windows Update",
  "Pilotes et installeurs téléchargés par UpKeep (NVIDIA, Dell, HP, ASUS, « Télécharger seulement »).": "Controladores e instaladores descargados por UpKeep (NVIDIA, Dell, HP, ASUS, «Solo descargar»).",
  "Pilotes non proposés : une stratégie de l’organisation les exclut de Windows Update (désactivez « Respecter les stratégies » pour passer outre).": "Controladores no ofrecidos: una directiva de la organización los excluye de Windows Update (desactiva «Respetar las directivas» para ignorarla).",
  "Plage horaire": "Franja horaria",
  "Planifier le redémarrage": "Programar el reinicio",
  "Plus d’actions": "Más acciones",
  "Plus tard": "Más tarde",
  "Point de restauration avant pilotes, firmware et mises à jour Windows": "Punto de restauración antes de controladores, firmware y actualizaciones de Windows",
  "Portée": "Ámbito",
  "Pour les pilotes Wi-Fi et Bluetooth Intel, installez Intel DSA (action ci-dessous).": "Para los controladores Wi-Fi y Bluetooth de Intel, instala Intel DSA (acción de abajo).",
  "Problème": "Problema",
  "Processeur": "Procesador",
  "Processus à fermer": "Proceso que cerrar",
  "Prochaine vérification {when}": "Próxima comprobación {when}",
  "Produit": "Producto",
  "Profil": "Perfil",
  "Profil : {name}": "Perfil: {name}",
  "Profil actif": "Perfil activo",
  "Profil activé à chaque démarrage d’UpKeep (ou via l’argument --profile=<id>).": "Perfil activado en cada inicio de UpKeep (o mediante el argumento --profile=<id>).",
  "Profil au lancement": "Perfil al iniciar",
  "Profils": "Perfiles",
  "Profils, règles, éléments ignorés, options par paquet…": "Perfiles, reglas, elementos ignorados, opciones por paquete…",
  "Progression": "Progreso",
  "Proposée par Windows Update quand votre PC est éligible ; UpKeep ouvre Windows Update pour la lancer.": "Ofrecida por Windows Update cuando tu PC es compatible; UpKeep abre Windows Update para iniciarla.",
  "Précédent": "Anterior",
  "Prête": "Lista",
  "Publiée le": "Publicada el",
  "Période": "Período",
  "Périphérique absent": "Dispositivo ausente",
  "Périphériques absents mémorisés": "Dispositivos ausentes memorizados",
  "Périphériques avec firmware": "Dispositivos con firmware",
  "Quarantaine des nouvelles versions": "Cuarentena de nuevas versiones",
  "Quitter": "Salir",
  "Raccourcis : Ctrl+R vérifier · Ctrl+F rechercher · Ctrl+A tout sélectionner · Entrée installer la sélection · Échap fermer": "Atajos: Ctrl+R comprobar · Ctrl+F buscar · Ctrl+A seleccionar todo · Intro instalar la selección · Esc cerrar",
  "Rappel de redémarrage": "Recordatorio de reinicio",
  "Rapport complet": "Informe completo",
  "Rapport créé.": "Informe creado.",
  "Rapport de diagnostic": "Informe de diagnóstico",
  "Rapport de sécurité": "Informe de seguridad",
  "Recharger l’interface": "Recargar la interfaz",
  "Recherche en cours…": "Buscando…",
  "Recherche globale": "Búsqueda global",
  "Recherche winget": "Búsqueda winget",
  "Rechercher": "Buscar",
  "Rechercher une page, une mise à jour, un réglage…": "Buscar una página, una actualización, un ajuste…",
  "Rechercher…": "Buscar…",
  "Rechercher… (Ctrl+F)": "Buscar… (Ctrl+F)",
  "Recherche…": "Buscando…",
  "Redémarrage": "Reinicio",
  "Redémarrage automatique": "Reinicio automático",
  "Redémarrage automatique prévu à {time}, après vos heures d’activité.": "Reinicio automático previsto a las {time}, después de tus horas activas.",
  "Redémarrage en attente": "Reinicio pendiente",
  "Redémarrage planifié": "Reinicio programado",
  "Redémarrage planifié {when}": "Reinicio programado {when}",
  "Redémarrer automatiquement après mes heures d’activité": "Reiniciar automáticamente después de mis horas activas",
  "Redémarrer dans": "Reiniciar en",
  "Redémarrer maintenant": "Reiniciar ahora",
  "Redémarrer à": "Reiniciar a las",
  "Redémarrer…": "Reiniciar…",
  "Relance de {path}": "Reiniciando {path}",
  "Relancer": "Volver a mostrar",
  "Relancer après la mise à jour": "Volver a abrir tras la actualización",
  "Reporte notifications et installations automatiques.": "Aplaza las notificaciones y las instalaciones automáticas.",
  "Respecter les stratégies de l’organisation": "Respetar las directivas de la organización",
  "Restauration de pilote": "Restauración de controlador",
  "Restaurer le pilote": "Restaurar el controlador",
  "Restaurer le pilote précédent ?": "¿Restaurar el controlador anterior?",
  "Rester dans la zone de notification à la fermeture": "Permanecer en el área de notificación al cerrar",
  "Rester sur la version majeure {major}": "Quedarse en la versión principal {major}",
  "Revenir à la version précédente ?": "¿Volver a la versión anterior?",
  "Revoir l’accueil": "Volver a ver la bienvenida",
  "Rien à installer.": "Nada que instalar.",
  "Rythme et démarrage": "Ritmo e inicio",
  "Règles": "Reglas",
  "Réaffichage": "Volver a mostrar",
  "Réafficher dans Windows Update": "Volver a mostrar en Windows Update",
  "Réessayer": "Reintentar",
  "Réessayer automatiquement après une erreur réseau": "Reintentar automáticamente tras un error de red",
  "Réessayer une fois une source en échec": "Reintentar una vez una fuente fallida",
  "Réglage": "Ajuste",
  "Réglages": "Ajustes",
  "Réglages d’origine": "Restablecer valores originales",
  "Résultats": "Resultados",
  "Résumé de la semaine": "Resumen de la semana",
  "Résumé hebdomadaire": "Resumen semanal",
  "Réussi": "Correcto",
  "SSD d’origine : firmware fourni par le constructeur du PC (voir Sources).": "SSD de fábrica: firmware proporcionado por el fabricante del PC (ver Fuentes).",
  "Sam": "Sáb",
  "Sans chiffrement, les données sont lisibles si le PC est volé.": "Sin cifrado, los datos se pueden leer si roban el PC.",
  "Santé": "Estado de salud",
  "Sauvegarde": "Copia de seguridad",
  "Selon la source": "Según la fuente",
  "Seul votre compte (et les administrateurs) peut y déposer des scripts. Cela revient à approuver d’avance les élévations de votre compte : un programme malveillant lancé sous votre session pourrait aussi s’en servir. Désactivez l’option pour supprimer la tâche.": "Solo tu cuenta (y los administradores) puede depositar scripts allí. Equivale a aprobar de antemano las elevaciones de tu cuenta: un programa malicioso ejecutado en tu sesión también podría usarlo. Desactiva la opción para eliminar la tarea.",
  "Seules les sources détectées sur ce PC sont proposées. Vous pourrez changer d’avis dans « Sources ».": "Solo se proponen las fuentes detectadas en este PC. Podrás cambiar de opinión en «Fuentes».",
  "Si un administrateur exclut les pilotes de Windows Update ou impose un serveur WSUS, UpKeep suit ces règles.": "Si un administrador excluye los controladores de Windows Update o impone un servidor WSUS, UpKeep sigue esas reglas.",
  "Signature numérique invalide ou éditeur inattendu : installation bloquée.": "Firma digital no válida o editor inesperado: instalación bloqueada.",
  "Site": "Sitio web",
  "Sombre": "Oscuro",
  "Source": "Fuente",
  "Source : endoflife.date. Un logiciel en fin de support ne reçoit plus de correctifs de sécurité.": "Fuente: endoflife.date. Un programa sin soporte ya no recibe correcciones de seguridad.",
  "Sources": "Fuentes",
  "Sources : Windows Update (classe Firmware) et l’outil constructeur s’il est configuré dans « Sources ».": "Fuentes: Windows Update (clase Firmware) y la herramienta del fabricante si está configurada en «Fuentes».",
  "Sources activées dans ce profil": "Fuentes activadas en este perfil",
  "Sources différentes uniquement ; les installations administrateur sont regroupées.": "Solo fuentes distintas; las instalaciones de administrador se agrupan.",
  "Sources d’alertes de sécurité": "Fuentes de alertas de seguridad",
  "Sources à surveiller": "Fuentes que vigilar",
  "Sous-système Windows pour Linux (noyau et outils) comparé aux versions publiées sur GitHub": "Subsistema de Windows para Linux (kernel y herramientas) comparado con las versiones publicadas en GitHub",
  "Statut": "Estado",
  "Suivant": "Siguiente",
  "Suivi par": "Seguido por",
  "Suivis": "Seguidos",
  "Support {brand}": "Soporte de {brand}",
  "Supprimer": "Eliminar",
  "Supprimer le profil « {name} » ?": "¿Eliminar el perfil «{name}»?",
  "Suspendre BitLocker pour un redémarrage avant un BIOS": "Suspender BitLocker durante un reinicio antes de una BIOS",
  "Suspendre les notifications 4 h": "Pausar las notificaciones 4 h",
  "Système": "Sistema",
  "Sécurité": "Seguridad",
  "Sécurité du poste": "Seguridad del equipo",
  "Sélectionner {name}": "Seleccionar {name}",
  "Tableau": "Tabla",
  "Taille": "Tamaño",
  "Thème": "Tema",
  "Total": "Total",
  "Toujours automatique": "Siempre automático",
  "Toujours bloquer sur batterie": "Bloquear siempre con batería",
  "Toujours ignorer": "Ignorar siempre",
  "Tous les logiciels installés, et le gestionnaire qui les suit.": "Todos los programas instalados y el gestor que los sigue.",
  "Tous les statuts": "Todos los estados",
  "Tout": "Todo",
  "Tout est à jour": "Todo está al día",
  "Tout est à jour.": "Todo está al día.",
  "Tout installer": "Instalar todo",
  "Tout mettre à jour": "Actualizar todo",
  "Tout sélectionner": "Seleccionar todo",
  "Toute la période": "Todo el período",
  "Toutes les sources": "Todas las fuentes",
  "Toutes les sources activées, sauf réglage propre à une source.": "Todas las fuentes activadas, salvo ajuste propio de una fuente.",
  "Toutes les {n} h": "Cada {n} h",
  "Type": "Tipo",
  "Tâche": "Tarea",
  "Tâche planifiée": "Tarea programada",
  "Téléchargement": "Descarga",
  "Téléchargement de {file}…": "Descargando {file}…",
  "Téléchargement lancé": "Descarga iniciada",
  "Téléchargements d’UpKeep": "Descargas de UpKeep",
  "Téléchargements d’UpKeep supprimés.": "Descargas de UpKeep eliminadas.",
  "Télécharger": "Descargar",
  "Télécharger seulement": "Solo descargar",
  "Téléchargé : {path}": "Descargado: {path}",
  "Un point de restauration système sera créé avant l’installation.": "Se creará un punto de restauración del sistema antes de la instalación.",
  "Un redémarrage est nécessaire pour finaliser certaines mises à jour.": "Es necesario reiniciar para completar algunas actualizaciones.",
  "Un redémarrage sera nécessaire ensuite.": "Después será necesario reiniciar.",
  "Une stratégie exclut les pilotes des mises à jour de qualité Windows Update.": "Una directiva excluye los controladores de las actualizaciones de calidad de Windows Update.",
  "Une tâche planifiée système exécute les installations administrateur d’UpKeep. Nécessaire pour les mises à jour automatiques qui demandent l’administrateur.": "Una tarea programada del sistema ejecuta las instalaciones de administrador de UpKeep. Necesaria para las actualizaciones automáticas que requieren administrador.",
  "Une version n’est proposée qu’après ce délai depuis sa publication (ou sa première détection). Les mises à jour de sécurité ne sont jamais retenues.": "Una versión solo se propone una vez transcurrido este plazo desde su publicación (o primera detección). Las actualizaciones de seguridad nunca se retienen.",
  "Unité": "Unidad",
  "Utilisateur": "Usuario",
  "Utilise les heures d’activité définies dans Windows Update.": "Usa las horas activas definidas en Windows Update.",
  "Utiliser la couleur d’accent de Windows": "Usar el color de énfasis de Windows",
  "Ven": "Vie",
  "Version": "Versión",
  "Version après": "Versión después",
  "Version avant": "Versión antes",
  "Version du pilote AMD Software: Adrenalin Edition installée": "Versión instalada del controlador AMD Software: Adrenalin Edition",
  "Version installée : {v}. AMD ne publie pas d’API de versions et son site bloque les accès automatiques : utilisez « Rechercher les mises à jour » dans AMD Software.": "Versión instalada: {v}. AMD no publica ninguna API de versiones y su sitio bloquea los accesos automáticos: usa «Buscar actualizaciones» en AMD Software.",
  "Version précise / retour arrière": "Versión concreta / reversión",
  "Version précédente": "Versión anterior",
  "Version {v}": "Versión {v}",
  "Versions épinglées": "Versiones fijadas",
  "Vider l’historique": "Vaciar el historial",
  "Voir les mises à jour": "Ver las actualizaciones",
  "Voir l’activité": "Ver la actividad",
  "Vue compacte": "Vista compacta",
  "Vue compacte des listes": "Listas compactas",
  "Vérification en cours : {list}…": "Comprobando: {list}…",
  "Vérification en cours…": "Comprobando…",
  "Vérification périodique des mises à jour : paquets, Windows, pilotes, firmware et BIOS.": "Comprobación periódica de actualizaciones: paquetes, Windows, controladores, firmware y BIOS.",
  "Vérifications simultanées": "Comprobaciones simultáneas",
  "Vérification…": "Comprobando…",
  "Vérifier": "Comprobar",
  "Vérifier au démarrage de l’application": "Comprobar al iniciar la aplicación",
  "Vérifier au réveil de veille et au retour du réseau": "Comprobar al salir de suspensión y al volver la red",
  "Vérifier maintenant": "Comprobar ahora",
  "Vérifier même quand UpKeep est fermé": "Comprobar incluso con UpKeep cerrado",
  "Vérifiez que vous avez votre clé de récupération BitLocker.": "Asegúrate de tener tu clave de recuperación de BitLocker.",
  "WSL : proposer les préversions": "WSL: ofrecer versiones preliminares",
  "WinGet : inclure les paquets à version inconnue": "WinGet: incluir paquetes con versión desconocida",
  "Windows": "Windows",
  "Windows Update est ouvert : cliquez sur « Télécharger et installer » si la version est proposée.": "Windows Update está abierto: haz clic en «Descargar e instalar» si se ofrece la versión.",
  "Windows continue de proposer les pilotes des périphériques branchés un jour puis retirés. Les oublier supprime ces propositions.": "Windows sigue ofreciendo controladores de dispositivos conectados una vez y luego retirados. Olvidarlos elimina esas propuestas.",
  "Windows demandera une seule élévation (UAC) pour tout le lot.": "Windows pedirá una sola elevación (UAC) para todo el lote.",
  "Windows mémorise tout périphérique déjà branché et continue de proposer ses pilotes.": "Windows recuerda cada dispositivo que se ha conectado y sigue ofreciendo sus controladores.",
  "Windows supprimera ces périphériques de sa mémoire. S’ils sont rebranchés, ils seront simplement redétectés.": "Windows eliminará estos dispositivos de su memoria. Si se vuelven a conectar, simplemente se detectarán de nuevo.",
  "Windows {family} version {v}": "Windows {family} versión {v}",
  "Zip local (journaux, rapports de plantage, paramètres) à joindre à un signalement. Rien n’est envoyé automatiquement.": "Zip local (registros, informes de errores, configuración) para adjuntar a un informe. No se envía nada automáticamente.",
  "[simulation] aucune commande n’a été exécutée.": "[simulación] no se ejecutó ningún comando.",
  "[simulation] {type} via {provider} :": "[simulación] {type} vía {provider}:",
  "absent": "ausente",
  "actif": "activo",
  "actif sur tous les profils": "activo en todos los perfiles",
  "actif · définitions de {n} jour(s)": "activo · definiciones de hace {n} día(s)",
  "active": "activa",
  "activé": "activado",
  "admin": "admin",
  "afficher": "mostrar",
  "aucun": "ninguno",
  "aujourd’hui à {time}": "hoy a las {time}",
  "aussi via {list}": "también vía {list}",
  "automatique": "automático",
  "batterie faible": "batería baja",
  "bientôt": "pronto",
  "chiffrement en cours": "cifrado en curso",
  "connexion limitée": "conexión de uso medido",
  "copie": "copia",
  "critique": "crítica",
  "demain à {time}": "mañana a las {time}",
  "désactivé": "desactivado",
  "désactivé pour : {list}": "desactivado para: {list}",
  "erreur": "error",
  "et {n} autre(s)…": "y {n} más…",
  "exploitée": "explotada",
  "expérimental": "experimental",
  "facultatif": "opcional",
  "heures": "horas",
  "hors plage horaire": "fuera de la franja horaria",
  "inconnu": "desconocido",
  "inconnu (BIOS hérité ?)": "desconocido (¿BIOS heredada?)",
  "inconnue": "desconocida",
  "installé": "instalado",
  "installée": "instalada",
  "jamais": "nunca",
  "je le ferai moi-même": "lo haré yo mismo",
  "jours": "días",
  "les oublier": "olvidarlos",
  "maintenu": "con soporte",
  "manuelle": "manual",
  "masquée": "oculta",
  "masquée(s) dans Windows Update": "oculta(s) en Windows Update",
  "minutes": "minutos",
  "mode démo": "modo demo",
  "nom du processus, ex. firefox": "nombre del proceso, p. ej. firefox",
  "non annoncée": "no anunciada",
  "non disponible": "no disponible",
  "non disponible (autre antivirus ?)": "no disponible (¿otro antivirus?)",
  "o": "B",
  "outil à installer": "herramienta que instalar",
  "par défaut ({n})": "predeterminado ({n})",
  "pilote(s) de périphériques absents": "controlador(es) de dispositivos ausentes",
  "plein écran / ne pas déranger": "pantalla completa / no molestar",
  "portable": "portátil",
  "prochaine {when}": "próxima {when}",
  "présent · version {v}": "presente · versión {v}",
  "préversion": "versión preliminar",
  "préversion(s)": "versión(es) preliminar(es)",
  "quarantaine": "cuarentena",
  "redémarrage": "reinicio",
  "reste sur la version {v}.x": "se queda en la versión {v}.x",
  "simulation": "simulación",
  "sur batterie": "con batería",
  "sur secteur": "con alimentación de red",
  "suspendu": "suspendido",
  "sécurité": "seguridad",
  "tentative {n}": "intento {n}",
  "terminé": "terminado",
  "toujours ignorée": "siempre ignorada",
  "version {v} ignorée": "versión {v} ignorada",
  "version(s) en quarantaine ({d} j)": "versión(es) en cuarentena ({d} d)",
  "vide": "vacío",
  "vérifié {when}": "comprobado {when}",
  "winget, Scoop, npm, pip, pipx, cargo, outils .NET et extensions VS Code. L’import réinstalle ce qui manque (suivi dans « Activité »).": "winget, Scoop, npm, pip, pipx, cargo, herramientas .NET y extensiones de VS Code. La importación reinstala lo que falta (seguimiento en «Actividad»).",
  "{name} installé": "{name} instalado",
  "{n} % de la capacité d’origine": "{n} % de la capacidad original",
  "{n} en cours": "{n} en curso",
  "{n} entrée(s)": "{n} entrada(s)",
  "{n} firmware/BIOS": "{n} firmware/BIOS",
  "{n} h": "{n} h",
  "{n} heure(s)": "{n} hora(s)",
  "{n} j": "{n} d",
  "{n} jour(s)": "{n} día(s)",
  "{n} ligne(s) précédente(s)": "{n} línea(s) anterior(es)",
  "{n} min": "{n} min",
  "{n} minutes": "{n} minutos",
  "{n} mise(s) à jour": "{n} actualización(es)",
  "{n} mise(s) à jour Windows": "{n} actualización(es) de Windows",
  "{n} mise(s) à jour corrigent une faille activement exploitée.": "{n} actualización(es) corrigen una vulnerabilidad explotada activamente.",
  "{n} mise(s) à jour de sécurité à installer.": "{n} actualización(es) de seguridad por instalar.",
  "{n} mise(s) à jour disponible(s)": "{n} actualización(es) disponible(s)",
  "{n} mise(s) à jour installée(s), {f} échec(s), {p} en attente, {q} en quarantaine.": "{n} actualización(es) instalada(s), {f} error(es), {p} pendiente(s), {q} en cuarentena.",
  "{n} mise(s) à jour, aucune urgente.": "{n} actualización(es), ninguna urgente.",
  "{n} mises à jour": "{n} actualizaciones",
  "{n} mises à jour lancées": "{n} actualizaciones iniciadas",
  "{n} paquet(s)": "{n} paquete(s)",
  "{n} pilote(s)": "{n} controlador(es)",
  "{n} pilote(s) proposés": "{n} controlador(es) ofrecido(s)",
  "{n} source(s) actives sur {total}.": "{n} fuente(s) activa(s) de {total}.",
  "{n} sélectionné(s)": "{n} seleccionado(s)",
  "{n} élément(s)": "{n} elemento(s)",
  "{p} : fin de support le {d}": "{p}: fin de soporte el {d}",
  "{p} n’est plus maintenu": "{p} ya no tiene soporte",
  "{s} s": "{s} s",
  "« {name} » ignorée": "«{name}» ignorada",
  "À propos": "Acerca de",
  "À surveiller": "A vigilar",
  "Échec": "Error",
  "Échec de la mise à jour": "Error de actualización",
  "Échec, nouvelle tentative dans 5 s": "Error, nuevo intento en 5 s",
  "Échecs": "Errores",
  "Éditeur": "Editor",
  "Élément": "Elemento",
  "État": "Estado",
  "État avant la mise à jour": "Estado antes de la actualización",
  "État du poste": "Estado del equipo",
  "Évite de devoir saisir la clé de récupération après la mise à jour du firmware.": "Evita tener que introducir la clave de recuperación tras actualizar el firmware.",
  "Pour : {name}": "Para: {name}",
  "Périphérique absent : {name}": "Dispositivo ausente: {name}",
  "démo": "demo",
  "Licence : PolyForm Noncommercial 1.0.0. Toute utilisation commerciale nécessite une licence commerciale.": "Licencia: PolyForm Noncommercial 1.0.0. Todo uso comercial requiere una licencia comercial.",
  "UpKeep {v} est prêt": "UpKeep {v} está listo",
  "La mise à jour sera installée à la fermeture d’UpKeep, ou tout de suite depuis « À propos ».": "La actualización se instalará al cerrar UpKeep, o de inmediato desde «Acerca de».",
  "UpKeep {v} est disponible": "UpKeep {v} está disponible",
  "Détails dans « À propos ».": "Detalles en «Acerca de».",
  "Dernière vérification : {date}": "Última comprobación: {date}",
  "Recherche d’une nouvelle version…": "Buscando una nueva versión…",
  "UpKeep est à jour.": "UpKeep está actualizado.",
  "La version {v} est disponible.": "La versión {v} está disponible.",
  "Téléchargement de la version {v}… {p} %": "Descargando la versión {v}… {p} %",
  "La version {v} est téléchargée : elle sera installée à la fermeture d’UpKeep.": "La versión {v} está descargada: se instalará al cerrar UpKeep.",
  "Échec de la recherche de mise à jour : {error}": "Error al buscar actualizaciones: {error}",
  "Redémarrer et installer": "Reiniciar e instalar",
  "Télécharger et installer": "Descargar e instalar",
  "Ouvrir la page de téléchargement": "Abrir la página de descarga",
  "Rechercher une mise à jour d’UpKeep": "Buscar actualizaciones de UpKeep",
  "Mettre à jour UpKeep automatiquement": "Actualizar UpKeep automáticamente",
  "Recherche les nouvelles versions publiées sur GitHub. La version installée les télécharge et les installe à sa fermeture ; les versions portable, MSI et ZIP signalent seulement la nouvelle version.": "Busca nuevas versiones publicadas en GitHub. La versión instalada las descarga y las instala al cerrarse; las versiones portable, MSI y ZIP solo avisan de la nueva versión.",
  "Rechercher des logiciels": "Buscar programas",
  "Trouvez un logiciel dans les catalogues de vos gestionnaires de paquets et installez-le.": "Busca un programa en los catálogos de tus gestores de paquetes e instálalo.",
  "Nom ou identifiant (ex. vlc, 7zip)": "Nombre o identificador (p. ej. vlc, 7zip)",
  "Logiciel à rechercher": "Programa que buscar",
  "Masquer les logiciels déjà installés": "Ocultar los programas ya instalados",
  "Catalogues": "Catálogos",
  "{name} n’est pas installé sur ce PC.": "{name} no está instalado en este PC.",
  "Aucun gestionnaire de paquets n’est installé sur ce PC (WinGet, Scoop ou Chocolatey).": "No hay ningún gestor de paquetes instalado en este PC (WinGet, Scoop o Chocolatey).",
  "{name} : {error}": "{name}: {error}",
  "Recherche dans les catalogues…": "Buscando en los catálogos…",
  "Tapez le nom d’un logiciel puis Entrée.": "Escribe el nombre de un programa y pulsa Intro.",
  "Aucun résultat pour « {q} ».": "No hay resultados para «{q}».",
  "Résultats de la recherche": "Resultados de la búsqueda",
  "en file": "en cola",
  "Chocolatey demande les droits administrateur.": "Chocolatey requiere permisos de administrador.",
  "Installer (admin)": "Instalar (admin)",
  "Installer": "Instalar",
  "Installation de {name} ajoutée à la file.": "Instalación de {name} añadida a la cola.",
  "Source indisponible : {name}": "Fuente no disponible: {name}",
  "Recherche refusée : 2 à 100 caractères, lettres, chiffres et . + # _ @ / -": "Búsqueda rechazada: de 2 a 100 caracteres, letras, cifras y . + # _ @ / -",
};
